### ISSUE TITLE
v3.0.0 Scalatest-dispatcher OutOfMemoryError running from Jenkins with +100k tests

### ISSUE THREAD

**Issue by bravegag** [scalatest/scalatest#1007]
Exception in thread "ScalaTest-dispatcher" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:445)
        at java.lang.StringBuffer.append(StringBuffer.java:312)
        at java.lang.StringBuffer.append(StringBuffer.java:97)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:459)
        at java.lang.StringBuffer.append(StringBuffer.java:340)
        at java.util.regex.Matcher.appendReplacement(Matcher.java:890)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replace(String.java:2228)
        at org.scalatest.tools.JUnitXmlReporter.xmlify(JUnitXmlReporter.scala:381)
        at org.scalatest.tools.JUnitXmlReporter.writeSuiteFile(JUnitXmlReporter.scala:77)
        at org.scalatest.tools.JUnitXmlReporter.apply(JUnitXmlReporter.scala:59)
        at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:243)
        at org.scalatest.DispatchReporter$Propagator$$anonfun$run$1.apply(DispatchReporter.scala:242)
        at scala.collection.immutable.List.foreach(List.scala:318)
        at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:242)
            at java.lang.Thread.run(Thread.java:745)

**Comment by eleansa** [comment]
Any luck with that?
