### ISSUE TITLE
Dotty Support

### ISSUE THREAD

**Issue by eaplatanios** [scalatest/scalatest#1138]
Is there any estimate on when we can expect Scalatest to work with Dotty? I assume the main limitation is dependence on macros?

Thank you!

**Comment by msoule** [comment]
Any update on this given the recent news about Scala 3?

**Comment by SethTisue** [comment]
I wouldn't expect the core team to give this any attention at least until after https://github.com/scalatest/scalatest/issues/1367 lands

but, perhaps a volunteer effort to add Dotty support would be welcome?

note that ScalaTest is already in the [Dotty community build](https://github.com/lampepfl/dotty-community-build)

**Comment by drdozer** [comment]
Sorry to resurrect this, but scalatest doesn't work for dotty right now (for me) because, I think, of the Position macro magic. I get:

```
[info] ExampleSpec *** ABORTED ***
[info]   java.lang.NoSuchMethodError: org.scalactic.source.Position$.here()Lorg/scalactic/source/Position;
[info]   at ExampleSpec.<init>(Test1.scala:10)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[info]   at java.base/java.lang.Class.newInstance(Class.java:584)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:435)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[info]   at sbt.TestRunner.run(TestFramework.scala:124)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
```

**Comment by gzoller** [comment]
Bump.  I’m working on moving my project to Dotty and I’ve currently got 100s of tests written in Scalatest for it.  I love this tool.  Any updates/news on plans and progress?

**Comment by SethTisue** [comment]
You might try using https://search.maven.org/artifact/dev.travisbrown/scalatest_0.22 — unofficial artifacts not blessed by ScalaTest maintainers, but perhaps useful as an interim measure (see also https://twitter.com/travisbrown/status/1221691735874719744)

**Comment by travisbrown** [comment]
I've updated my unofficial artifacts for scalatestplus-scalacheck-1-14 and discipline-scalatest to depend on the new officially-published ScalaTest 3.1.1: https://twitter.com/travisbrown/status/1232298961215643653

**Comment by mpilquist** [comment]
FYI, here's a set of dependencies that work without needing @travisbrown's shims -- trick is to use `scalacheck-1-14` via `withDottyCompat`, which requires ignoring its transitives:

```scala
    libraryDependencies ++= Seq(
      "org.scalatest" %%% "scalatest" % "3.1.1" % "test",
      ("org.scalatestplus" %%% "scalacheck-1-14" % "3.1.1.1" % "test")
        .intransitive()
        .withDottyCompat(scalaVersion.value),
      ("org.scalacheck" %%% "scalacheck" % "1.14.3" % "test").withDottyCompat(scalaVersion.value)
    ),
```

**Comment by plokhotnyuk** [comment]
Is there any guide how to migrate sources of tests to be cross-compiled with Dotty?

Currently it returns hundreds compilation errors with some suggestions to add imports for some implicits like: 
```
[error] -- [E007] Type Mismatch Error: /home/andriy/Projects/com/github/plokhotnyuk/rtree2d/rtree2d-core/src/test/scala/com/github/plokhotnyuk/rtree2d/core/GeometryCheckers.scala:12:47 
[error] 12 |    PropertyCheckConfiguration(minSuccessful = 1000)
[error]    |                                               ^^^^
[error]    |    Found:    (1000 : Int)
[error]    |    Required: org.scalactic.anyvals.PosInt
[error]    |
[error]    |    The following import might make progress towards fixing the problem:
[error]    |
[error]    |      import org.scalactic.anyvals.PosInt.apply
[error]    |             
[error] -- [E008] Member Not Found Error: /home/andriy/Projects/com/github/plokhotnyuk/rtree2d/rtree2d-core/src/test/scala/com/github/plokhotnyuk/rtree2d/core/GeometryCheckers.scala:14:57 
[error] 14 |    "asked to calculate distance from point to an RTree" should {
[error]    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value should is not a member of String, but could be made available as an extension method.
[error]    |
[error]    |One of the following imports might make progress towards fixing the problem:
[error]    |
[error]    |  import org.scalatest.matchers.should.Matchers.convertToStringShouldWrapper
[error]    |  import org.scalatest.matchers.should.Matchers.convertToAnyShouldWrapper
[error]    |  import org.scalatest.matchers.should.Matchers.convertToStringShouldWrapperForVerb
[error]    |         
[error] -- Error: /home/andriy/Projects/com/github/plokhotnyuk/rtree2d/rtree2d-core/src/test/scala/com/github/plokhotnyuk/rtree2d/core/GeometryCheckers.scala:23:9 
[error] 23 |        }
[error]    |         ^
[error]    |no implicit argument of type org.scalactic.source.Position was found for parameter pos of method forAll in trait ScalaCheckDrivenPropertyChecks
[error]    |
[error]    |The following import might make progress towards fixing the problem:
[error]    |
[error]    |  import org.scalactic.source.Position.here
```
But adding them doesn't help at all...

**Comment by JacopoGobbi** [comment]
Hi, may I ask what is the status of this issue?
I was just experimenting with Dotty `0.24.0-RC1` and with my simple [project](https://github.com/JacopoGobbi/scala3dotty/blob/master/src/test/scala/io/github/jacopogobbi/MainTests.scala) ran into 2 issues:
- `value shouldBe is not a member of Boolean` error when trying to use `shouldBe`
- The new scala ["quiet syntax"](https://dotty.epfl.ch/docs/reference/other-new-features/control-syntax) (removal of parenthesis) did not seem to work well when trying to run tests, I had to add parenthesis back in my app Main object and in the [method I was testing](https://github.com/JacopoGobbi/scala3dotty/blob/master/src/main/scala/io/github/jacopogobbi/Main.scala#L36)

Feel free to clone the project to see for yourself. I am just curious if there is anybody more experienced that can (help me) understand if:
1. These are Dotty limitations and do not relate to Scalatest.
1. Such issues are related to cross compilation issues.
1. Scalatest support for Dotty is still not present or it is buggy.

Thanks!

**Comment by SethTisue** [comment]
@JacopoGobbi (although I'm not a ScalaTest maintainer) I suggest you open individual tickets on those two issues you mentioned. the reports will be likelier to get attention if they come with MCVEs

**Comment by JacopoGobbi** [comment]
@SethTisue , I gave an example, I am not trying to find the solution to the issue, just to understand if Dotty is supported which is part of this issue because with my test it was not.

**Comment by SethTisue** [comment]
@JacopoGobbi  Dotty is itself experimental and a moving target, so basically nothing involving Dotty qualifies as "officially supported". Regardless, yes ScalaTest is normally expected to work with Dotty, at least most of the time! If something specific is going wrong, specific tickets that document the specific problems (hopefully leading to eventual fixes, too!) are welcome.

**Comment by JacopoGobbi** [comment]
Thanks everyone, I was able to successfully create and run scalatests on a sample project using the latest (3.0.0-M3) Scala 3 version:
For anyone interested: https://github.com/JacopoGobbi/scala3dotty
Feel free to fork.

**Comment by SethTisue** [comment]
Scala 3.0.0-RC1 is on Maven Central. scala-xml and scalacheck have published. I hope we can expect ScalaTest to publish before too long...?

**Comment by bvenners** [comment]
@SethTisue Yep, unfortunately some of our macros broke in 3.0.0-RC1. Chee Seng fixed those last night, but we still have failing tests. We think it is good enough to deploy now, but Sonatype kept timing out (after a half hour each time). So he'll continue in his morning. Should have the release out within 12 hours I'd estimate.

**Comment by bvenners** [comment]
This is out now:

https://oss.sonatype.org/content/groups/public/org/scalatest/scalatest-core_3.0.0-RC1/3.2.4/

The scalatestplus modules will be out soon.

**Comment by bvenners** [comment]
Well we may have rushed too much because this was RC1. There were a lot of breakages we had to fix from 3.0.0-M3, so we did that, and in the process may have done a source breaking change. Any use of futureValue requires parens now in 3.2.4, so we may need to do another quick release tomorrow.
