### ISSUE TITLE
java.util.TimerThread not stopped after test is finished

### ISSUE THREAD

**Issue by giampaolotrapasso** [scalatest/scalatest#1175]
After running multiple times the same test inside sbt on my project, I got a Metaspace OOM error. I removed every pending thread and at the end only the "Timer-0" thread survived at the end of the test. 

To make the investigation easier, I created a very small project with just two tests 
[https://github.com/giampaolotrapasso/TimerIssue](https://github.com/giampaolotrapasso/TimerIssue) and I repeated the `test` command five times.

As you can see from the picture, every time a new timer get allocated without removing the previous one.
![threads](https://user-images.githubusercontent.com/7675964/27582457-43057fe0-5b31-11e7-93af-3a892eb1a471.png)
HProf files are [available](https://github.com/giampaolotrapasso/TimerIssue/tree/master/hprof)

My very rough analysis -not scalatest expert at all- concluded that this pending thread should cause the metaspace retention and so the OOM. The timer is fired inside `SuiteSortingReporter` that is allocated with the [sbt test task](https://github.com/scalatest/scalatest/blob/208278abc69cc4bcb03c6bd4e25b876211678520/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L666) 

Any thoughts on this? Did I misunderstood something?
Thank you in advance

**Comment by MeiSign** [comment]
I run into the same issue with scalatest 3.0.4 have you found any workaround to solve this issue?

**Comment by quiquedeveloper** [comment]
same issue here

**Comment by bvenners** [comment]
I believe we fixed this, but released it in a SNAP release only. Will get it into a real release soon.

**Comment by retronym** [comment]
Hi @bvenners,

I re-diagnosed this problem in the context of debugging https://github.com/sbt/sbt/issues/4166.

FTR, I also found potential classloader leaks when Log4J was used in SBT's temporary classloader for tests that could be worked around with `sbt -Dlog4j2.disable.jmx=true -Dlog4j.shutdownHookEnabled=false`.

I was using https://github.com/sbt/librarymanagement/tree/v1.1.5 as a test project.

```
sbt -Dlog4j2.disable.jmx=true -Dlog4j.shutdownHookEnabled=false -J-XX:MaxMetaspaceSize=256M -J-XX:MetaspaceSize=256M -J-verbose:gc -J-XX:+PrintGCDetails -J-XX:+HeapDumpOnOutOfMemoryError

sbt:LM Root> ; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec; testOnly sbt.internal.librarymanagement.EvictionWarningSpec
...
[GC (Last ditch collection) [PSYoungGen: 0K->0K(651264K)] 153599K->153599K(2049536K), 0.0061225 secs] [Times: user=0.01 sys=0.00, real=0.01 secs]
[Full GC (Last ditch collection) [PSYoungGen: 0K->0K(651264K)] [ParOldGen: 153599K->153022K(1398272K)] 153599K->153022K(2049536K), [Metaspace: 228187K->228187K(1280000K)], 0.2143661 secs] [Times: user=0.54 sys=0.01, real=0.21 secs]
[error] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Metaspace
[error] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[error] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:207)
```

This project is using `scalatest_2.12-3.0.5.jar`, the most recent release advertised.

I don't see any calls to `timer.cancel()` added in https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/SuiteSortingReporter.scala.

Ideally there would be a mode to avoid creating the timer at all, in the case that no timeout is specified.

Apart from leaking the thread itself, the classloader that runs the tests is leaked. As the metadata can't be reclaimed, the `OutOfMemoryError` eventually happens.

![image](https://user-images.githubusercontent.com/65551/42671065-8a3b954c-86a1-11e8-8616-6f958827f67f.png)

![image](https://user-images.githubusercontent.com/65551/42671070-90ede372-86a1-11e8-8c24-81672f1820d5.png)

**Comment by retronym** [comment]
A workaround is to use `fork in test := true` to run tests in a child process.

**Comment by retronym** [comment]
Another workaround is to wait for, or trigger, a full GC, which will stop no-longer referenced timer threads, and in turn make the classloader and corresponding metaspace collectable. A similar issue exists with a cache internal to `ResourceBundle.getBundle` (called by ScalaTest), that retains classlaoder references until weak reference cleanup.

More details in https://github.com/sbt/sbt/issues/4166#issuecomment-404722257

**Comment by gleber-da** [comment]
I am hitting this issue too.

**Comment by cheeseng** [comment]
Fyi I added an alternative PR here: 

https://github.com/scalatest/scalatest/pull/1774

Feel free to comment, and if possible, help to verify if it fixes the issue.

Cheers.
