### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by cquiroz** [scalatest/scalatest#1180]
I'm having troubles building scalatest. First I get this missing values errors

```
[error] /Users/cquiroz/Projects/scalatest/project/scalatest.scala:131: not found: value pgpSecretRing
[error]     pgpSecretRing := file(getGPGFilePath),
[error]     ^
[error] /Users/cquiroz/Projects/scalatest/project/scalatest.scala:132: not found: value pgpPassphrase
[error]     pgpPassphrase := getGPGPassphase
[error]     ^
[error] two errors found
```

And after commenting I get a class cast exception:
```
java.lang.ClassCastException: Cannot cast com.typesafe.sbt.SbtPgp$ to sbt.Plugin
	at java.lang.Class.cast(Class.java:3369)
	at sbt.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:20)
```

Should scalatest be buildable right out of the box or am I missing some steps?

**Comment by cheeseng** [comment]
@cquiroz commenting them out seems to be the right thing to do, it is used only for deployment.  Truth to be told, I never encountered the second error you seeing, I think perhaps you can comment out the following plugin line too: 

https://github.com/scalatest/scalatest/blob/3.0.x/project/plugins.sbt#L1

FYI: Here's what other complained about the error you described: 

https://github.com/sbt/sbt-pgp/issues/67

Also, just a reminder, if you intended to submit PR against 3.0.3, please use 3.0.x branch.

Thanks.

**Comment by 2m** [comment]
I get the same error, as I have

```
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.1.0")
```

in my global sbt config. I need to comment out this plugin from my global config to load the scalatest project successfully.
