### ISSUE TITLE
ScalaTest won't work with ScalaJS

### ISSUE THREAD

**Issue by joan38** [scalatest/scalatest#1284]
```
> sbt
[info] Loading settings from idea.sbt ...
[info] Loading global plugins from /Users/joangoyeau/.sbt/1.0/plugins
[info] Updating {file:/Users/joangoyeau/.sbt/1.0/plugins/}global-plugins...
[info] Done updating.
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/joangoyeau/Code/test/project
[info] Updating {file:/Users/joangoyeau/Code/test/project/}test-build...
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to test (in build file:/Users/joangoyeau/Code/test/)
[info] sbt server started at 127.0.0.1:5565
sbt:test> test
[info] Updating {file:/Users/joangoyeau/Code/test/}testJVM...
[info] Updating {file:/Users/joangoyeau/Code/test/}testJS...
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-library_2.12/0.6.21/scalajs-library_2.12-0.6.21.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.4/scalactic_2.12-3.0.4.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.4/scalatest_2.12-3.0.4.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-test-interface_2.12/0.6.21/scalajs-test-interface_2.12-0.6.21.jar ...
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-test-interface_2.12;0.6.21!scalajs-test-interface_2.12.jar (435ms)
[info] 	[SUCCESSFUL ] org.scalactic#scalactic_2.12;3.0.4!scalactic_2.12.jar(bundle) (617ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-compiler_2.12.4/0.6.21/scalajs-compiler_2.12.4-0.6.21.jar ...
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-compiler_2.12.4;0.6.21!scalajs-compiler_2.12.4.jar (720ms)
[info] 	[SUCCESSFUL ] org.scalatest#scalatest_2.12;3.0.4!scalatest_2.12.jar(bundle) (3397ms)
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-library_2.12;0.6.21!scalajs-library_2.12.jar (3471ms)
[info] Done updating.
[info] Updating {file:/Users/joangoyeau/Code/test/}test...
[info] Done updating.
[info] Done updating.
[info] Fast optimizing /Users/joangoyeau/Code/test/test/.js/target/scala-2.12/test-test-fastopt.js
[info] Fast optimizing /Users/joangoyeau/Code/test/test/.jvm/target/scala-2.12/test-test-fastopt.js
[error] dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.58.dylib
[error]   Referenced from: /usr/local/bin/node
[error]   Reason: image not found
[error] java.io.IOException: Stream closed
[error] 	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
[error] 	at java.io.OutputStream.write(OutputStream.java:116)
[error] 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[error] 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[error] 	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
[error] 	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.pipeVMData(ExternalJSEnv.scala:97)
[error] 	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:167)
[error] 	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:71)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1004)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 134
[error] 	at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:119)
[error] 	at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:168)
[error] 	at org.scalajs.sbtplugin.FrameworkDetector.detect(FrameworkDetector.scala:71)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSTestFrameworkSettings$1(ScalaJSPluginInternal.scala:1004)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (testJS/test:loadedTestFrameworks) java.io.IOException: Stream closed
[error] (testJVM/test:loadedTestFrameworks) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 134
[error] Total time: 24 s, completed 04-Dec-2017 16:32:2
```

See demo project:
https://github.com/joan38/scalajs-scalatest-issue

Thanks

**Comment by jducoeur** [comment]
I'm confused -- that project doesn't appear to have any code in it...

**Comment by joan38** [comment]
Hi @jducoeur 

It doesn't matter, but I added some tests for the sake of it.

Cheers

**Comment by cheeseng** [comment]
@joan38 I tried the project and it seems to work on my machine (running Ubuntu Linux): 

```
cheeseng@cheeseng-GP60-2OD:~/git/scalajs-scalatest-issue$ sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /home/cheeseng/git/scalajs-scalatest-issue/project
[info] Updating {file:/home/cheeseng/git/scalajs-scalatest-issue/project/}scalajs-scalatest-issue-build...
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-ir_2.12/0.6.21/scalajs-ir_2.12-0.6.21.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-js-envs_2.12/0.6.21/scalajs-js-envs_2.12-0.6.21.jar ...
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-sbt-test-adapter_2.12/0.6.21/scalajs-sbt-test-adapter_2.12-0.6.21.jar ...
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-js/sbt-scalajs/scala_2.12/sbt_1.0/0.6.21/jars/sbt-scalajs.jar ...
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-ir_2.12;0.6.21!scalajs-ir_2.12.jar (1827ms)
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-sbt-test-adapter_2.12;0.6.21!scalajs-sbt-test-adapter_2.12.jar (2250ms)
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-js-envs_2.12;0.6.21!scalajs-js-envs_2.12.jar (2506ms)
[info] 	[SUCCESSFUL ] org.scala-js#sbt-scalajs;0.6.21!sbt-scalajs.jar (5814ms)
[info] downloading https://repo1.maven.org/maven2/org/scala-js/scalajs-tools_2.12/0.6.21/scalajs-tools_2.12-0.6.21.jar ...
[info] 	[SUCCESSFUL ] org.scala-js#scalajs-tools_2.12;0.6.21!scalajs-tools_2.12.jar (1488ms)
[info] Done updating.
[info] Loading settings from build.sbt ...
[info] Set current project to scalajs-scalatest-issue (in build file:/home/cheeseng/git/scalajs-scalatest-issue/)
[info] sbt server started at 127.0.0.1:5271
sbt:scalajs-scalatest-issue> test
[info] Updating {file:/home/cheeseng/git/scalajs-scalatest-issue/}testJS...
[info] Updating {file:/home/cheeseng/git/scalajs-scalatest-issue/}scalajs-scalatest-issue...
[info] Updating {file:/home/cheeseng/git/scalajs-scalatest-issue/}testJVM...
[info] Done updating.
[info] Done updating.
[info] Compiling 1 Scala source to /home/cheeseng/git/scalajs-scalatest-issue/test/.js/target/scala-2.12/test-classes ...
[info] Done updating.
[info] Compiling 1 Scala source to /home/cheeseng/git/scalajs-scalatest-issue/test/.jvm/target/scala-2.12/test-classes ...
[warn] there were two deprecation warnings (since 2.12.0); re-run with -deprecation for details
[warn] there were two deprecation warnings (since 2.12.0); re-run with -deprecation for details
[warn] one warning found
[warn] one warning found
[info] Done compiling.
[info] Done compiling.
[info] Fast optimizing /home/cheeseng/git/scalajs-scalatest-issue/test/.js/target/scala-2.12/test-test-fastopt.js
[info] Fast optimizing /home/cheeseng/git/scalajs-scalatest-issue/test/.jvm/target/scala-2.12/test-test-fastopt.js
[info] ExampleSpec:
[info] A Stack
[info] - should pop values in last-in-first-out order
[info] - should throw NoSuchElementException if an empty stack is popped
[info] ExampleSpec:
[info] A Stack
[info] - should pop values in last-in-first-out order
[info] - should throw NoSuchElementException if an empty stack is popped
[info] Run completed in 10 seconds, 19 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Run completed in 10 seconds, 19 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
```
I wonder if your node is working, may be you can try: 

```
node -v
```

and see what you get?

**Comment by joan38** [comment]
After `brew upgrade node` it worked. Thanks

I was actually trying to run JVM tests and even `testJVM/test` needs node installed, do you know why?

**Comment by cheeseng** [comment]
@joan38 I have no idea why is that so, scala-js probably is better fit for this question.  :)

**Comment by joan38** [comment]
Cheers @cheeseng I will ask there. Closing this issue now.
