### ISSUE TITLE
`org.scalatest.tools.TaskRunner` throws JavaScriptException in Scala.js if the test class name is encoded

### ISSUE THREAD

**Issue by Atry** [scalatest/scalatest#1397]
# Reproduction

### project/build.properties
```
sbt.version=1.2.0
```

### project/plugins.sbt
``` sbt
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.5.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.24")
```

### build.sbt

``` sbt
// shadow sbt-scalajs' crossProject(JSPlatform, JVMPlatform) and CrossType from Scala.js 0.6.x
import sbtcrossproject.CrossPlugin.autoImport.{crossProject, CrossType}

lazy val share = crossProject(JSPlatform, JVMPlatform)
  .crossType(CrossType.Pure)
  .settings(libraryDependencies += "org.scalatest" %%% "scalatest" % "3.0.5" % Test)

lazy val shareJS = share.js
lazy val shareJVM = share.jvm
```

### share/src/test/scala/mypackage/My$minusTest.scala

``` scala
package mypackage
import org.scalatest._
class My$minusTest extends FreeSpec with Matchers {
  "outer" - {
    "inner" in {
      succeed
    }
  }
}
```

## Run the following command

```
sbt test
```

## Expected output

No error.

## Actual output

```
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins
[info] Loading settings for project scalatest-js-crash-build from plugins.sbt ...
[info] Loading project definition from /private/tmp/scalatest-js-crash/project
[info] Loading settings for project scalatest-js-crash from build.sbt ...
[info] Set current project to scalatest-js-crash (in build file:/private/tmp/scalatest-js-crash/)
[info] Updating ...
[info] Updating shareJS...
[info] Updating shareJVM...
[info] Done updating.
[info] Done updating.
[info] Done updating.
[info] Compiling 1 Scala source to /private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/test-classes ...
[info] Compiling 1 Scala source to /private/tmp/scalatest-js-crash/share/.jvm/target/scala-2.12/test-classes ...
[info] Done compiling.
[info] Done compiling.
[info] My$minusTest:
[info] outer
[info] - inner
[info] Run completed in 826 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Fast optimizing /private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js
[error] org.scalajs.testcommon.RPCCore$RPCException
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:69)
[error] 	at scala.Option.foreach(Option.scala:257)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:67)
[error] 	at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:47)
[error] 	at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:48)
[error] 	at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:47)
[error] 	at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31)
[error] Caused by: scala.scalajs.js.JavaScriptException: TypeError: Cannot read property 'prototype' of undefined
[error] 	at <jscode>.$newJSObjectWithVarargs(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:478)
[error] 	at org.scalajs.testinterface.TestUtils$.newInstance(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:5322)
[error] 	at org.scalatest.tools.TaskRunner.executionFuture(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:21321)
[error] 	at org.scalatest.tools.TaskRunner.execute(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:21283)
[error] 	at <jscode>.{anonymous}()(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:5488)
[error] 	at scala.scalajs.runtime.AnonFunction1.apply(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:28570)
[error] 	at <jscode>.{anonymous}()(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:4131)
[error] 	at scala.scalajs.runtime.AnonFunction1.apply(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:28570)
[error] 	at <jscode>.{anonymous}()(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:13610)
[error] 	at scala.scalajs.runtime.AnonFunction1.apply(/private/tmp/scalatest-js-crash/share/.js/target/scala-2.12/share-test-fastopt.js:28570)
[error] Could not run test mypackage.My$minusTest: org.scalajs.testcommon.RPCCore$RPCException
[info] EndTestGroupErrorEvent(mypackage.My$minusTest, null
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:69)
[info] scala.Option.foreach(Option.scala:257)
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:67)
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:47)
[info] org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:48)
[info] org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:47)
[info] org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:31))
[error] java.lang.NullPointerException
[error] 	at sbt.JUnitXmlTestsListener$TestSuite.$anonfun$stop$2(JUnitXmlTestsListener.scala:114)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.List.foreach(List.scala:389)
[error] 	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:35)
[error] 	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:35)
[error] 	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:44)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at sbt.JUnitXmlTestsListener$TestSuite.stop(JUnitXmlTestsListener.scala:110)
[error] 	at sbt.JUnitXmlTestsListener.$anonfun$writeSuite$2(JUnitXmlTestsListener.scala:232)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at sbt.JUnitXmlTestsListener.withTestSuite(JUnitXmlTestsListener.scala:153)
[error] 	at sbt.JUnitXmlTestsListener.writeSuite(JUnitXmlTestsListener.scala:232)
[error] 	at sbt.JUnitXmlTestsListener.endGroup(JUnitXmlTestsListener.scala:207)
[error] 	at sbt.TestRunner.$anonfun$run$8(TestFramework.scala:129)
[error] 	at sbt.TestRunner.$anonfun$run$8$adapted(TestFramework.scala:129)
[error] 	at sbt.TestFramework$.$anonfun$safeForeach$1(TestFramework.scala:150)
[error] 	at sbt.TestFramework$.$anonfun$safeForeach$1$adapted(TestFramework.scala:149)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:944)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at sbt.TestFramework$.safeForeach(TestFramework.scala:149)
[error] 	at sbt.TestRunner.safeListenersCall(TestFramework.scala:135)
[error] 	at sbt.TestRunner.run(TestFramework.scala:129)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error] 	at sbt.TestFunction.apply(TestFramework.scala:294)
[error] 	at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NullPointerException
[info] Run completed in 329 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error during tests:
[error] 	mypackage.My-Test
[error] (shareJS / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 19 s, completed Aug 7, 2018 2:56:58 PM
```

Copied from https://github.com/scala-js/scala-js/issues/3423, as @sjrd suggested

**Comment by cheeseng** [comment]
@Atry thanks for reporting the problem, I can reproduce it in the current 3.0.5 but not in the latest branch that we're working on, do you mind to try 3.0.6-SNAP2 and see if it works?

Thanks.

**Comment by Atry** [comment]
It seems that 3.0.6-SNAP2 has not been published for Scala.js

```
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/twer/.sbt/1.0/plugins
[info] Loading settings for project st-build from plugins.sbt ...
[info] Loading project definition from /private/tmp/st/project
[info] Loading settings for project st from build.sbt ...
[info] Set current project to st (in build file:/private/tmp/st/)
[info] Updating shareJS...
[info] My$minusTest:
[info] outer
[info] - inner
[info] Run completed in 655 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[warn] 	module not found: org.scalatest#scalatest_sjs0.6_2.12;3.0.6-SNAP2
[warn] ==== local: tried
[warn]   /Users/twer/.ivy2/local/org.scalatest/scalatest_sjs0.6_2.12/3.0.6-SNAP2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatest/scalatest_sjs0.6_2.12/3.0.6-SNAP2/scalatest_sjs0.6_2.12-3.0.6-SNAP2.pom
[warn] ==== activator-launcher-local: tried
[warn]   /Users/twer/.activator/repository/org.scalatest/scalatest_sjs0.6_2.12/3.0.6-SNAP2/ivys/ivy.xml
[warn] ==== activator-local: tried
[warn]   /usr/local/Cellar/typesafe-activator/1.3.2/libexec/repository/org.scalatest/scalatest_sjs0.6_2.12/3.0.6-SNAP2/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalatest/scalatest_sjs0.6_2.12/3.0.6-SNAP2/scalatest_sjs0.6_2.12-3.0.6-SNAP2.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.scalatest/scalatest_sjs0.6_2.12/3.0.6-SNAP2/ivys/ivy.xml
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scalatest#scalatest_sjs0.6_2.12;3.0.6-SNAP2: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.scalatest:scalatest_sjs0.6_2.12:3.0.6-SNAP2 (/private/tmp/st/build.sbt#L5)
[warn] 		  +- share:share_sjs0.6_2.12:0.1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalatest#scalatest_sjs0.6_2.12;3.0.6-SNAP2: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2519)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (shareJS / update) sbt.librarymanagement.ResolveException: unresolved dependency: org.scalatest#scalatest_sjs0.6_2.12;3.0.6-SNAP2: not found
[error] Total time: 15 s, completed Aug 14, 2018 2:32:47 PM
```

**Comment by cheeseng** [comment]
@Atry Interesting, our SNAP2 seems to go to here: 

https://repo1.maven.org/maven2/org/scalatest/scalatestjs_sjs0.6_2.12/3.0.6-SNAP2/

(notice the scalatestjs vs scalatest)

I'll try to to see why our latest branch is deploying with the extra 'js', and shall redeploy artifacts without the 'js' postfix if possible, will ping here again once that becomes available.

I am sorry for the confusion caused.

**Comment by cheeseng** [comment]
@Atry I have uploaded the missing artifacts, can you try again?

**Comment by Atry** [comment]
Cannot reproduce in Scalatest 3.0.6-SNAP2

**Comment by tpolecat** [comment]
I'm seeing similar behavior in 3.1.0-SNAP13

```
[error] org.scalajs.testcommon.RPCCore$RPCException: java.lang.RuntimeException: Cannot load suite class: gem.UserTargetSpec
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:79)
[error]         at scala.Option.foreach(Option.scala:257)
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:77)
[error]         at org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:57)
[error]         at org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:60)
[error]         at org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:57)
[error]         at org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:34)
[error] Caused by: java.lang.RuntimeException: Cannot load suite class: gem.UserTargetSpec
[error]         at <jscode>.$c_jl_RuntimeException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:24308)
[error]         at <jscode>.$c_jl_RuntimeException.$c_jl_Throwable.init___T__jl_Throwable__Z__Z(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:24426)
[error]         at java.lang.RuntimeException.<init>(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:34125)
[error]         at <jscode>.{anonymous}()(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:23557)
[error]         at scala.scalajs.runtime.AnonFunction0.apply(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:31515)
[error]         at org.scalatest.tools.TaskRunner.executionFuture(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:23560)
[error]         at org.scalatest.tools.TaskRunner.execute(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:23543)
[error]         at <jscode>.{anonymous}()(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:6194)
[error]         at scala.scalajs.runtime.AnonFunction1.apply(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:31543)
[error]         at <jscode>.{anonymous}()(/Users/rnorris/Scala/ocs3/modules/core/js/target/scala-2.12/core-test-fastopt.js:4815)
[error] Could not run test gem.UserTargetSpec: org.scalajs.testcommon.RPCCore$RPCException: java.lang.RuntimeException: Cannot load suite class: gem.UserTargetSpec
[info] EndTestGroupErrorEvent(gem.UserTargetSpec, java.lang.RuntimeException: Cannot load suite class: gem.UserTargetSpec
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$4(RPCCore.scala:79)
[info] scala.Option.foreach(Option.scala:257)
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1(RPCCore.scala:77)
[info] org.scalajs.testcommon.RPCCore.$anonfun$handleMessage$1$adapted(RPCCore.scala:57)
[info] org.scalajs.testcommon.Serializer$.withInputStream(Serializer.scala:60)
[info] org.scalajs.testcommon.RPCCore.handleMessage(RPCCore.scala:57)
[info] org.scalajs.testadapter.ComJSEnvRPC$$anon$1.run(ComJSEnvRPC.scala:34))
[error] java.lang.NullPointerException
[error]         at sbt.JUnitXmlTestsListener$TestSuite.$anonfun$stop$2(JUnitXmlTestsListener.scala:114)
[error]         at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error]         at scala.collection.immutable.List.foreach(List.scala:388)
[error]         at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:34)
[error]         at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:34)
[error]         at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:43)
[error]         at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error]         at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error]         at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error]         at sbt.JUnitXmlTestsListener$TestSuite.stop(JUnitXmlTestsListener.scala:110)
[error]         at sbt.JUnitXmlTestsListener.$anonfun$writeSuite$3(JUnitXmlTestsListener.scala:235)
[error]         at scala.Option.map(Option.scala:146)
[error]         at sbt.JUnitXmlTestsListener.withTestSuite(JUnitXmlTestsListener.scala:153)
[error]         at sbt.JUnitXmlTestsListener.writeSuite(JUnitXmlTestsListener.scala:235)
[error]         at sbt.JUnitXmlTestsListener.endGroup(JUnitXmlTestsListener.scala:207)
[error]         at sbt.TestRunner.$anonfun$run$8(TestFramework.scala:129)
[error]         at sbt.TestRunner.$anonfun$run$8$adapted(TestFramework.scala:129)
[error]         at sbt.TestFramework$.$anonfun$safeForeach$1(TestFramework.scala:150)
[error]         at sbt.TestFramework$.$anonfun$safeForeach$1$adapted(TestFramework.scala:149)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at sbt.TestFramework$.safeForeach(TestFramework.scala:149)
[error]         at sbt.TestRunner.safeListenersCall(TestFramework.scala:135)
[error]         at sbt.TestRunner.run(TestFramework.scala:129)
[error]         at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[error]         at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[error]         at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error]         at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[error]         at sbt.TestFunction.apply(TestFramework.scala:294)
[error]         at sbt.Tests$.processRunnable$1(Tests.scala:347)
[error]         at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[error]         at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.NullPointerException
```
