### ISSUE TITLE
Ignored tests in wrapped TestNG Suites cause RuntimeException to be thrown in JUnitXmlReporter

### ISSUE THREAD

**Issue by tferi-da** [scalatest/scalatest#1408]
When running the [adapted RS-TCK test suite](https://github.com/reactive-streams/reactive-streams-jvm/tree/master/tck#scala) (which has a couple ignored test cases) ScalaTest dumps the following on he console:
```
Reporter completed abruptly with an exception after receiving event: SuiteCompleted(Ordinal(0, 594),<TestSuite>,<package>.<TestSuite>,Some(<package>.<TestSuite>),Some(438),Some(MotionToSuppress),Some(TopOfClass(<package>.<TestSuite>)),None,None,pool-1-thread-1,1534934582834). java.lang.RuntimeException: unexpected event [TestIgnored(Ordinal(0, 565),<TestSuite>,<package>.<TestSuite>,Some(<package>.<TestSuite>),untested_spec202_blackbox_shouldAsynchronouslyDispatch,untested_spec202_blackbox_shouldAsynchronouslyDispatch,Some(IndentedText(- untested_spec202_blackbox_shouldAsynchronouslyDispatch,untested_spec202_blackbox_shouldAsynchronouslyDispatch,1)),Some(TopOfMethod(<package>.<TestSuite>,public void <package>.<TestSuite>.untested_spec202_blackbox_shouldAsynchronouslyDispatch())),None,pool-1-thread-1,1534934582691)]
	at org.scalatest.tools.JUnitXmlReporter.unexpected(JUnitXmlReporter.scala:495)
	at org.scalatest.tools.JUnitXmlReporter.processTest(JUnitXmlReporter.scala:326)
	at org.scalatest.tools.JUnitXmlReporter.getTestsuite(JUnitXmlReporter.scala:166)
	at org.scalatest.tools.JUnitXmlReporter.writeSuiteFile(JUnitXmlReporter.scala:76)
	at org.scalatest.tools.JUnitXmlReporter.apply(JUnitXmlReporter.scala:59)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by satyadeepthi** [comment]
I have the same issue as well. Did u find a solution?
