### ISSUE TITLE
The here macro to materialize a source file position slows down compilation

### ISSUE THREAD

**Issue by retronym** [scalatest/scalatest#1418]
I'm [working](https://github.com/retronym/scala/pull/28) on instrumentation for the compiler to attribute compilation time to compilation of particular file/line/method/implicits/macros.

I've used this tool to analyse the compilation of https://github.com/guardian/frontend, which is a relatively large application that uses Play and ScalaTest.

One thing that stood out is that 1.5% of compilation time is attributed to the expansion of the `here` macro in ScalaTest, which is implemented by `genPosition`.

https://github.com/scalatest/scalatest/blob/a7673db180bf14e757d476fb06df4aa17948e1a8/scalactic-macro/src/main/scala/org/scalactic/source/PositionMacro.scala#L35-L63

It might be possible to reduce the cost of this macro, by reducing the number of calls to `newTermName` and avoiding generating a big nested select that must be typechecked to find the `Position` class.

Here's a more direct way to generate a call to `scala.Symbol.apply`, for instance.
```
scala> def impl(c: Context): c.Tree = { import c.universe._; Apply(typeOf[Symbol.type].decl(TermName("apply")), Literal(Constant("blah")))}; def m: Any = macro impl
<console>:28: warning: method Apply in trait Trees is deprecated (since 2.10.1): use q"$sym(..$args)" instead
       def impl(c: Context): c.Tree = { import c.universe._; Apply(typeOf[Symbol.type].decl(TermName("apply")), Literal(Constant("blah")))}; def m: Any = macro impl
                                                             ^
impl: (c: scala.reflect.macros.blackbox.Context)c.Tree
defined term macro m: Any

scala> m
res1: Any = 'blah
```

**Comment by retronym** [comment]
![image](https://user-images.githubusercontent.com/65551/46644431-91cd1d00-cbc3-11e8-82b6-f34db17365a8.png)

**Comment by bvenners** [comment]
@retronym Thanks for the idea (and the pretty diagram). I've assigned this to Chee Seng.

**Comment by retronym** [comment]
I'm looking more closely for the bottleneck. So far, I noticed this stack trace:

```
"ForkJoinPool-11-worker-1" #25 daemon prio=5 os_prio=31 tid=0x00007fc9783fb000 nid=0xa617 runnable [0x000070000597a000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Throwable.fillInStackTrace(Native Method)
	at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
	- locked <0x000000078b8b89d8> (a java.lang.ClassNotFoundException)
	at java.lang.Throwable.<init>(Throwable.java:287)
	at java.lang.Exception.<init>(Exception.java:84)
	at java.lang.ReflectiveOperationException.<init>(ReflectiveOperationException.java:75)
	at java.lang.ClassNotFoundException.<init>(ClassNotFoundException.java:82)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	- locked <0x00000006c385e8a0> (a java.lang.Object)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	- locked <0x00000006c3858e18> (a java.lang.Object)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	- locked <0x000000078b269ce0> (a scala.reflect.internal.util.ScalaClassLoader$URLClassLoader)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:2649)
	at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1510)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1474)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1428)
	at java.util.ResourceBundle.findBundle(ResourceBundle.java:1428)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1370)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:782)
	at org.scalactic.Resources$.resourceBundle$lzycompute(Resources.scala:8)
	- locked <0x000000078b8b81f0> (a org.scalactic.Resources$)
	at org.scalactic.Resources$.resourceBundle(Resources.scala:8)
	at org.scalactic.Resources$.pleaseDefineScalacticFillFilePathnameEnvVar(Resources.scala:256)
	at org.scalactic.source.PositionMacro$.genPosition(PositionMacro.scala:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers.$anonfun$resolveJavaReflectionRuntime$4(JavaReflectionRuntimes.scala:34)
	at scala.reflect.macros.runtime.JavaReflectionRuntimes$JavaReflectionResolvers$$Lambda$1522/318026163.apply(Unknown Source)
	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime(Macros.scala:811)
	at scala.tools.nsc.typechecker.Macros.macroExpandWithRuntime$(Macros.scala:787)
```

**Comment by retronym** [comment]
I've come back to looking at this.

I've found some inefficiencies in compiler that can reduce the overhead of macro calls a little: https://github.com/retronym/scala/tree/topic/macro-opt

After that, I'm measuring the benefit of having this macro [use lower-level APIs](https://github.com/retronym/scalactic-sandbox/commits) to generate the tree.

I'm measuring all this with https://github.com/scala/compiler-benchmark/pull/92 and

```
  269  for V in eb6ce1a; do sbt 'set scalaVersion in compilation := "2.12.9-bin-'$V'-SNAPSHOT"' 'prof hot -psource=@/code/compiler-benchmark/scalactic.args -f1 -wi 4 -i 5 -pextraArgs=-Ystop-after:typer|-Ycache-macro-class-loader:always'; done
  270  for V in eb6ce1a; do sbt 'set scalaVersion in compilation := "2.12.9-bin-'$V'-SNAPSHOT"' 'hot -psource=@/code/compiler-benchmark/scalactic.args -f1 -wi 4 -i 5 -pextraArgs=-Ystop-after:typer|-Ycache-macro-class-loader:always'; done
```

**Comment by retronym** [comment]
Scala Version | Macro Version | Performance (ms) | Relative performance 
--------------|---------------|--------------------|----------------------
Baseline | Baseline | 401ms | 1x 
https://github.com/retronym/scala/pull/47 | Baseline | 262ms | 1.91x 
https://github.com/retronym/scala/pull/47 | Custom | 137ms | 2.92x

**Comment by cheeseng** [comment]
@retronym The improvements seems very significant!  I wonder if the low level classes are available in 2.10?  If not we may need to generate the Position source based on Scala version where old scala version that doesn't support it will use the old way but newer scala version shall use the new one, the change will still binary compatible with 2.12.8, right?

**Comment by retronym** [comment]
@cheeseng The API moved around between 2.10 and 2.11.

This implementation uses a small source compatibility hack to compile against 2.10-2.12.

https://github.com/retronym/scalactic-sandbox/blob/master/src/main/scala/org/scalactic/source/PositionMacro.scala

Alternatively, your suggestion to make Scala version dependent source files would work.

**Comment by retronym** [comment]
I have proposed the compiler changes for 2.12.9: https://github.com/scalatest/scalatest/issues/1418#issuecomment-495543079

**Comment by retronym** [comment]
@cheeseng Another change that I forgot to recommend is to make the implementation of the `here` macro in _2.12 and _2.13 versions of Scalatest accept a `scala.reflect.macros.blackbox.Context`. This tells the compiler that the macro does not require the expanded expression to have a type more specific than the return type of the `macro def` itself, and it also tells implicit search that the macro need not be expanded during the implicit search itself, it only need by expanded after an implicit is decided upon.

**Comment by cheeseng** [comment]
@retronym Noted with thanks, I am eager to try to get this into 3.1.x, asap.

**Comment by retronym** [comment]
@cheeseng This is all in 3.1, I'll close this ticket now. Thanks!

**Comment by retronym** [comment]
(You might want to update the Milestone and other labels)
