### ISSUE TITLE
Original error message replaced when using TimeLimitedTests trait

### ISSUE THREAD

**Issue by NikolajsCmihuns** [scalatest/scalatest#1421]
Original error message replaced when using def `org.scalatest.concurrent.Eventually.eventually` and `org.scalatest.concurrent.TimeLimitedTests` trait.

Use this project as example: [https://github.com/NikolajsCmihuns/test_scalatest](https://github.com/NikolajsCmihuns/test_scalatest)
test files - `/test_scalatest/specs/src/test/scala/*.scala`

Output from TimeLimitedSpec (**mixes in TimeLimitedTests trait**):

> [info] Custom error messages
[info] - must be preserved when test fails *** FAILED *** (2 seconds, 59 milliseconds)
[info]   The test did not complete within the specified 2 seconds time limit. (TimeLimitedSpec.scala:9)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:432)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)
[info]   at org.scalatest.concurrent.Eventually.eventually$(Eventually.scala:391)
[info]   at TimeLimitedSpec.eventually(TimeLimitedSpec.scala:4)
........
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: org.scalatest.exceptions.TestFailedException: My error message
......

Output from WithoutTimeLimitSpec (**does not mix in TimeLimitedTests trait**):
> [info] - must be preserved when test fails *** FAILED *** (2 seconds, 58 milliseconds)
[info]   The code passed to eventually never returned normally. Attempted 14 times over 2.041572782 seconds. Last failure message: My error message. (WithoutTimeLimitSpec.scala:6)
[info]   org.scalatest.exceptions.TestFailedDueToTimeoutException:
[info]   at org.scalatest.concurrent.Eventually.tryTryAgain$1(Eventually.scala:432)
[info]   at org.scalatest.concurrent.Eventually.eventually(Eventually.scala:439)

TimeLimitedSpec has failing `eventually { assert(1 == 2, "My error message") }` assertion(retries 2 sec.) and timeLimit(5 sec.) which is not breached. BUT in output custom error message is displayed in stacktrace bottom and also message on top of output is `The test did not complete within the specified 2 seconds time limit` which is not true in this case - there was not time out breach and time out set is not even 2 seconds, it is 5 seconds.

Such behaviour also makes scalatest html report (see TimeLimitedSpec_html.png below) incorrect by hiding original message completely (**this is especially bad when using scalatest to write automated selenium tests and custom error message are crucial**)
[TimeLimitedSpec_html_report.png](https://user-images.githubusercontent.com/15145641/46827947-9ac81500-cda2-11e8-9f1d-4031626f370e.png)
**Message:** in report should include `My error message` instead, which is the real cause

Look at WithoutTimeLimitSpec_html_report.png below
[WithoutTimeLimitSpec_html_report.png](https://user-images.githubusercontent.com/15145641/46828261-7caee480-cda3-11e8-9be0-ff56431ebe1f.png)
**Message:** in report includes `My error message` which is correct

Possible cause of decribed issue:
when using `org.scalatest.concurrent.Eventually.eventually { ... }` it throws `TestFailedDueToTimeoutException` exception. It then get's modified in 
https://github.com/scalatest/scalatest/blob/a7673db180bf14e757d476fb06df4aa17948e1a8/scalatest/src/main/scala/org/scalatest/concurrent/TimeLimitedTests.scala#L158

**Comment by NikolajsCmihuns** [comment]
What about creating new custom exception type here (instead of TestFailedDueToTimeoutException)
https://github.com/scalatest/scalatest/blob/a7673db180bf14e757d476fb06df4aa17948e1a8/scalatest/src/main/scala/org/scalatest/concurrent/TimeLimits.scala#L240

and then here match against it https://github.com/scalatest/scalatest/blob/a7673db180bf14e757d476fb06df4aa17948e1a8/scalatest/src/main/scala/org/scalatest/concurrent/TimeLimitedTests.scala#L158

Thus we will not update all exception that match against `org.scalatest.exceptions.ModifiableMessage[_] with TimeoutField`

**Comment by NikolajsCmihuns** [comment]
@cheeseng @bvenners, please review
