### ISSUE TITLE
Scala 2.13.0-M5 + 3.0.6-SNAP3 + fork in Test := true shows lots of stdout messages

### ISSUE THREAD

**Issue by seratch** [scalatest/scalatest#1423]
Thank you for the release. After upgrading to Scala 2.13.0-M5 + ScalaTest 3.0.6-SNAP3, ScalaTest started showing lots of the following stdout messages. The situation occurs in my projects which enab le `fork in Test := true` in `build.sbt`. You can easily reproduce the situation by having `fork in Test := true` in `build.sbt`.

No effect on test results. Just showing lots of stdout messages.

```
Reporter completed abruptly with an exception after receiving event: TestSucceeded(Ordinal(0, 3),HelloSpec,example.scalate.HelloSpec,Some(example.scalate.HelloSpec),should work fine with scalate,should work fine with scalate,Vector(),Some(300),Some(IndentedText(- should work fine with scalate,should work fine with scalate,0)),Some(LineInFile(23,HelloSpec.scala,Some(Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.))),Some(example.scalate.HelloSpec),None,pool-1-thread-1-ScalaTest-running-HelloSpec,1539507465483).
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1286)
	at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1231)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1427)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1577)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:302)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by SethTisue** [comment]
I've noticed this as well

**Comment by kailuowang** [comment]
Is there any workaround? this is blocking Cats from getting on the M5 train.
I tried run `-CNCXEHLOPQRM cats.tests.NullReporter` in which `cats.tests.NullReporter` does nothing on any event, still same error. And we can't run tests with fork in test to false, it OOM on travis.

**Comment by cheeseng** [comment]
Hi all, I am looking into this now, will see if I can find the cause.

**Comment by cheeseng** [comment]
FYI: I released 3.0.6-SNAP5, please try to see if it fixes this issue.

Thanks.

**Comment by SethTisue** [comment]
fixes it for me!
