### ISSUE TITLE
How to force Generators to produce distinct values? (v3.1.0-SNAP8)

### ISSUE THREAD

**Issue by agilesteel** [scalatest/scalatest#1541]
ScalaTest v3.1.0-SNAP8

Hi, the equivalent code works in ScalaCheck, but in ScalaTest the Generators produce no values. My suspicion is that it is related to immutable Randomizers. How would one work around this?

```scala
import org.scalatest._
import org.scalatest.prop._

sealed abstract class Distinct extends Product with Serializable

object Distinct {
  def precondition[T](t: T*): Boolean =
    t.distinct.size == t.size

  final case class Two[T](first: T, second: T) extends Distinct {
    require(precondition(first, second))
  }

  object Two {
    implicit def gen[T: Generator]: Generator[Distinct.Two[T]] = {
      val g = implicitly[Generator[T]]

      for {
        first <- g
        second <- g
        // filters everything out due to immutable Randomizers
        if Distinct.precondition(first, second)
      } yield Distinct.Two(first, second)
    }
  }
}
```

**Comment by bvenners** [comment]
Can you show an example of it not working? This worked:

```
scala> val gen = implicitly[Generator[Distinct.Two[Int]]]
gen: org.scalatest.prop.Generator[com.artima.pbtdemos.Distinct.Two[Int]] = org.scalatest.prop.Generator$$anon$10@76d5e07

scala> gen.samples(10)
res0: List[com.artima.pbtdemos.Distinct.Two[Int]] = List(Two(2144718489,-1481307159), Two(-239210052,1002062177), Two(-140412985,728188652), Two(-1862964972,-1831265802), Two(956828503,48287477), Two(1954560491,-1555527690), Two(1234857101,-203684754), Two(259307289,173625172), Two(1726298598,-955591445), Two(2032211416,-1953774650))
```

**Comment by agilesteel** [comment]
Nice catch, I'm getting the same when calling `samples`, however if I use the Generator (both explicitly or implicitly) in `forAll` I'm getting the following:

```Scala
import org.scalatest._
import org.scalatest.funsuite._
import org.scalatest.prop._

class SetSuite extends AnyFunSuite with Matchers with PropertyChecks {
  test("adding the same element twice should simply ignore the input") {
    forAll /*(Distinct.Two.gen[String])*/ { distinct: Distinct.Two[String] =>
      import distinct._

      Set(first, second, second) shouldBe Set(first, second)
      Set(first, second, second).size shouldBe 2

      Set(first, second, first) shouldBe Set(first, second)
      Set(first, second, first).size shouldBe 2
    }
  }
}
```

This is what I'm getting:

```Scala
[info] SetSuite:                                                                     
[info] - adding the same element twice should simply ignore the input *** FAILED ***
[info]   java.lang.IllegalStateException: A Generator produced by calling filter or withFilter on another Generator (possibly by using an 'if' clause in a for expression) has filtered out 100000 objects in a row in its next method, so aborting. Please define the Generator without using filter or withFilter.
[info]   at org.scalatest.prop.Generator$$anon$11.loop$2(Generator.scala:373)                                       
[info]   at org.scalatest.prop.Generator$$anon$11.next(Generator.scala:379)                                     
[info]   at org.scalatest.prop.Generator$$anon$9.next(Generator.scala:220)
[info]   at org.scalatest.prop.Generator$$anon$10.next(Generator.scala:308)                   
[info]   at org.scalatest.enablers.UnitPropCheckerAsserting$PropCheckerAssertingImpl.loop$1(PropCheckerAsserting.scala:152)
[info]   at org.scalatest.enablers.UnitPropCheckerAsserting$PropCheckerAssertingImpl.checkForAll(PropCheckerAsserting.scala:215)
[info]   at org.scalatest.enablers.UnitPropCheckerAsserting$PropCheckerAssertingImpl.check1(PropCheckerAsserting.scala:634)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:724)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:716)
[info]   at user.CleanSetSuite.forAll(CleanSetSuite.scala:7)
[info]   ...
[info] Run completed in 1 second, 203 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
```

**Comment by agilesteel** [comment]
Any luck with this?

**Comment by agilesteel** [comment]
I'm really curious about this one. Any updates?

**Comment by bvenners** [comment]
@agilesteel Sorry I didn't notice your reply until now. I investigated and the problem isn't caused by the immutable nature of the Randomizer, but by the fact that we do edges first, and so they keep showing up as empty strings, given there's just one edge for String. I'll try a recursion approach next.

**Comment by bvenners** [comment]
@agilesteel I'm going to assign this to Chee Seng to investigate tonight. @cheeseng this does work:

```
  object Two {
    implicit def gen[T: Generator]: Generator[Distinct.Two[T]] = {
      val g = implicitly[Generator[T]]

      for {
        first <- g
        second <- g
        third = if (second == "") "42".asInstanceOf[T] else second
        if Distinct.precondition(first, third)
      } yield Distinct.Two(first, third)
    }
  }
```

My theory was that given String has exactly one edge, an empty string, that will always be tried first for the String generator given any Randomizer. But after that they should vary. If you stick a println in the forAll after the second line (of agilesteel's original code above), you'll see it is retrying two empty strings over and over. It correctly gives up after 100,000 such attempts. That last part is a feature. Please take a look and see if you can figure out why it gets stuck on empty string.

**Comment by agilesteel** [comment]
@bvenners awesome! Thanks for your time!

**Comment by cheeseng** [comment]
@bvenners @agilesteel fyi The reason is under current design, the 'first' and 'second' of the following code will always use the same SizeParam meter: 

for {
        first <- g
        second <- g
        if Distinct.precondition(first, second)
      } yield Distinct.Two(first, second)

While the size is 0, unfortunately, there's only one String that meet the size which is "", causing it to always fail.  I'll try to see if we can workaround this problem.

**Comment by cheeseng** [comment]
FYI Here's an experimental possible fix: 

https://github.com/cheeseng/scalatest/commit/cf0d061ca87126939cd8a622d9777e689552ecdc
