### ISSUE TITLE
Original failure message is not shown for Cancelled test in html report when using Retries trait

### ISSUE THREAD

**Issue by NikolajsCmihuns** [scalatest/scalatest#1621]
When mixing in **Retries** trait to the suite  and test initially fails, but passes after retry, there is no original failure message  in html report due to which retry was done. 
The only info presented is:

> Test canceled because flickered: initially failed, but succeeded on retry

which is not so informative for the report. However, notice that original failure can be seen from console reporter if test is executed e.g. in terminal and one have in build.sbt the following

```scala
testOptions in Test := Seq(
    Tests.Argument(TestFrameworks.ScalaTest, "-o") //write results to the standard output
)
```

In html report original failure information is necessary to deal with flaky tests and potentially fix them.
Have a look at example Spec code which shows described issue:

```scala
import org.scalatest.{MustMatchers, Outcome, Retries, WordSpec}
class RetrySpec extends WordSpec with Retries with MustMatchers {
  override def withFixture(test: NoArgTest): Outcome = withRetry {
    super.withFixture(test)
  }
  var counter = 0
  "RetrySpec" must {
    "retry spec" in {
      counter += 1
      if (counter == 1)
        List(1,2,3) mustBe List(4,5,6)
      else
        List(1,2,3) mustBe List(1,2,3)
    }
  }
}
```

sbt config
```scala

scalaVersion :="2.12.8",

libraryDependencies ++= Seq(
"org.scalatest" %% "scalatest" % "3.0.8" % Test
) 

testOptions in Test := Seq(
    Tests.Argument(TestFrameworks.ScalaTest, "-h"),
    Tests.Argument(TestFrameworks.ScalaTest, "target/test-reports-html"),
    Tests.Argument(TestFrameworks.ScalaTest, "-u"),
    Tests.Argument(TestFrameworks.ScalaTest, "target/test-reports"),
    Tests.Argument(TestFrameworks.ScalaTest, "-oDF")
)
```

HTML report:
```
**Message**:	Test canceled because flickered: initially failed, but succeeded on retry
**Line**:	(Retries.scala:349)
**Exception**:	org.scalatest.exceptions.TestCanceledException
org.scalatest.Canceled$.apply(Outcome.scala:518)
org.scalatest.Retries.withRetry(Retries.scala:349)
org.scalatest.Retries.withRetry$(Retries.scala:344)
com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
org.scalatest.Retries.withRetry(Retries.scala:205)
org.scalatest.Retries.withRetry$(Retries.scala:205)
com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
com.somecompany.somesystem.RetrySpec.withFixture(RetrySpec.scala:8)
org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
scala.collection.immutable.List.foreach(List.scala:392)
org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
scala.collection.immutable.List.foreach(List.scala:392)
org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
org.scalatest.Suite.run(Suite.scala:1124)
org.scalatest.Suite.run$(Suite.scala:1106)
org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
org.scalatest.SuperEngine.runImpl(Engine.scala:518)
org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
org.scalatest.WordSpec.run(WordSpec.scala:1881)
org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:748)
**Cause**:	org.scalatest.exceptions.TestFailedException
**Message**:	Test canceled because flickered: initially failed, but succeeded on retry
org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
org.scalatest.MustMatchers$AnyMustWrapper.mustBe(MustMatchers.scala:6919)
com.somecompany.somesystem.RetrySpec.$anonfun$new$2(RetrySpec.scala:17)
org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
org.scalatest.Transformer.apply(Transformer.scala:22)
org.scalatest.Transformer.apply(Transformer.scala:20)
org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
com.somecompany.somesystem.RetrySpec.super$withFixture(RetrySpec.scala:8)
com.somecompany.somesystem.RetrySpec.$anonfun$withFixture$1(RetrySpec.scala:8)
org.scalatest.Retries.withRetry(Retries.scala:345)
org.scalatest.Retries.withRetry$(Retries.scala:344)
com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
org.scalatest.Retries.withRetry(Retries.scala:205)
org.scalatest.Retries.withRetry$(Retries.scala:205)
com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
com.somecompany.somesystem.RetrySpec.withFixture(RetrySpec.scala:8)
org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
scala.collection.immutable.List.foreach(List.scala:392)
org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
scala.collection.immutable.List.foreach(List.scala:392)
org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
org.scalatest.Suite.run(Suite.scala:1124)
org.scalatest.Suite.run$(Suite.scala:1106)
org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
org.scalatest.SuperEngine.runImpl(Engine.scala:518)
org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
org.scalatest.WordSpec.run(WordSpec.scala:1881)
org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:748)
```

Terminal report (notice presence of original exception):
> Cause: org.scalatest.exceptions.TestFailedException: List(1, 2, 3) was not equal to List(4, 5, 6)

```
[info] RetrySpec
[info] - must retry spec !!! CANCELED !!! (31 milliseconds)
[info]   Test canceled because flickered: initially failed, but succeeded on retry (Retries.scala:349)
[info]   org.scalatest.exceptions.TestCanceledException:
[info]   at org.scalatest.Canceled$.apply(Outcome.scala:518)
[info]   at org.scalatest.Retries.withRetry(Retries.scala:349)
[info]   at org.scalatest.Retries.withRetry$(Retries.scala:344)
[info]   at com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
[info]   at org.scalatest.Retries.withRetry(Retries.scala:205)
[info]   at org.scalatest.Retries.withRetry$(Retries.scala:205)
[info]   at com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
[info]   at com.somecompany.somesystem.RetrySpec.withFixture(RetrySpec.scala:8)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite.run(Suite.scala:1124)
[info]   at org.scalatest.Suite.run$(Suite.scala:1106)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: org.scalatest.exceptions.TestFailedException: List(1, 2, 3) was not equal to List(4, 5, 6)
[info]   at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:343)
[info]   at org.scalatest.MustMatchers$AnyMustWrapper.mustBe(MustMatchers.scala:6919)
[info]   at com.somecompany.somesystem.RetrySpec.$anonfun$new$2(RetrySpec.scala:17)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at com.somecompany.somesystem.RetrySpec.super$withFixture(RetrySpec.scala:8)
[info]   at com.somecompany.somesystem.RetrySpec.$anonfun$withFixture$1(RetrySpec.scala:8)
[info]   at org.scalatest.Retries.withRetry(Retries.scala:345)
[info]   at org.scalatest.Retries.withRetry$(Retries.scala:344)
[info]   at com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
[info]   at org.scalatest.Retries.withRetry(Retries.scala:205)
[info]   at org.scalatest.Retries.withRetry$(Retries.scala:205)
[info]   at com.somecompany.somesystem.RetrySpec.withRetry(RetrySpec.scala:5)
[info]   at com.somecompany.somesystem.RetrySpec.withFixture(RetrySpec.scala:8)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]   at org.scalatest.WordSpec.runTest(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]   at org.scalatest.WordSpec.runTests(WordSpec.scala:1881)
[info]   at org.scalatest.Suite.run(Suite.scala:1124)
[info]   at org.scalatest.Suite.run$(Suite.scala:1106)
[info]   at org.scalatest.WordSpec.org$scalatest$WordSpecLike$$super$run(WordSpec.scala:1881)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]   at org.scalatest.WordSpec.run(WordSpec.scala:1881)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:304)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[info]   at java.lang.Thread.run(Thread.java:748)
[info] ScalaTest
[info] Run completed in 3 seconds, 266 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 1, ignored 0, pending 0
[info] No tests were executed.
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0, Canceled 1
[success] Total time: 17 s, completed Jul 4, 2019 9:29:46 AM
```

**Comment by NikolajsCmihuns** [comment]
looks like the fix can be done in HtmlReporter.getHTMLForCause. Generic  type Throwable is handled but there can be scalatest exceptions like TestFailedException there with valuable information like ```lazy val message``` which contains the true explanation why test failed
