### ISSUE TITLE
Replacement for using symbols as property matchers for 2.13+

### ISSUE THREAD

**Issue by jrudolph** [scalatest/scalatest#1679]
As symbol literals are deprecated from 2.13+, it might make sense to think about a replacement. Could there be a type-safe but less verbose replacement of BePropertyMatchers? E.g. so that you could write

```scala
xyz should be(_.isEmpty)
```

**Comment by bvenners** [comment]
@jrudolph I have struggled to figure out what to do about the tick mark. I did that originally because at the time I felt it was important to demonstrate to dynamic language enthusiasts that you could do that sort of thing in a static language also. And it was kind of a social experiment to see what users would prefer to use, a type safe approach (BePropertyMatcher) that requires more code versus a dynamic approach (reflection) that was more concise. My impression is that the vast majority of usages chose conciseness and convenience of the dynamic approach over the verbosity of the type safe approach.

But I grew to not like the reflection stuff over time and I think this may be an opportunity to move away from it. I think there is a lot of code using this, so one thing we could do is rewrite 'empty to empty, which has existed for years but many may not be aware of that. If we could figure out other common ones we could add a few more `BePropertyMatchers`, `HavePropertyMatcher`s, etc., and rewrite those to something pretty. Then for the rest we could rewrite to something that works like `Symbol("foo")`. Or we could shorten that, but I'd kind of rather to not add anything to shorten it to the ScalaTest library, just because it is using reflection and it would be nice to move away from it.

The other thing I would like to explore is can we get fancy in ScalaFix such that we write the BePropertyMatcher there right above where it would be used. We'd need to do the reflection in ScalaFix, but maybe that's possible.

As far as xyz shouldBe(_.isEmpty), I wouldn't want to go in that direction because it both doesn't read nicely as English in the code and you don't get a nice error message if it fails. You may as well write xyz.isEmpty shouldBe true. (Of course for empty you can say "xyz shouldBe empty" right now, but for something non-empty this applies!) In this case also you could get a good error message from an assertion:

```
scala> import org.scalatest._
import org.scalatest._

scala> import Assertions._
import Assertions._

scala> assert(List(1, 2, 3).isEmpty)
org.scalatest.exceptions.TestFailedException: List(1, 2, 3) was not empty
  at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:528)
  at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:527)
  at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1387)
  at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:501)
  ... 39 elided
```

**Comment by francisdb** [comment]
What about `should be('right)`, is there an alternative for that?

**Comment by devyn** [comment]
What do you think about using macros? It should be possible to do something that parses and looks readable but also allows you access to the property names, which is what you need for the good error messages.

**Comment by bvenners** [comment]
We could make a string interpolator, like be *"empty". Yuck. I had been leaning towards moving away from the dynamic matchers. There were always static alternatives, BePropertyMatcher in this case (also HavePropertyMatcher in the have case). Perhaps we could use macros to make those easier to generate. Then could just make a string interpolator that generates a symbol like sym"empty".

**Comment by devyn** [comment]
What I was thinking would be actually yes, to get rid of the dynamic matching entirely, but also to use a macro to generate the BePropertyMatcher or HavePropertyMatcher. For example, in

```scala
should have (
  foo (3),
  bar (4)
)
```

`have` could be a macro, it would see `foo` most likely as either an ident or select AST node, and it would create a HavePropertyMatcher that would get the `foo` property from the object as well as be able to insert `"foo"` as a String where needed automatically. I believe because it's generated code it should be type safe, and no reflection is involved. I haven't tested it out myself though.

**Comment by gabrieljones** [comment]
> I had been leaning towards moving away from the dynamic matchers. There were always static alternatives, BePropertyMatcher in this case (also HavePropertyMatcher in the have case). Perhaps we could use macros to make those easier to generate. Then could just make a string interpolator that generates a symbol like sym"empty".

The failure report on a reflective `should have` test is just so nice and descriptive. I often go out of my way to refactor other assertions into reflective `should have` tests for this reason alone.
