### ISSUE TITLE
java.lang.NoClassDefFoundError: org/scalatest/tools/Runner

### ISSUE THREAD

**Issue by phrmoy** [scalatest/scalatest#1718]
Running Ubuntu 19.10 with Intellij Community 2019.2.3, Java SDK 13.0.1, scala SDK 2.13.1, scalatest 3.0.8, scalactic 3.0.8. This is not an SBT project, it's a pure idea/scala project.

Is this JetBrains issue within their `org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner` object?

```
Testing started at 5:15 PM ...
/usr/lib/jvm/jdk-13.0.1/bin/java -javaagent:/snap/intellij-idea-community/177/lib/idea_rt.jar=37109:/snap/intellij-idea-community/177/bin -Dfile.encoding=UTF-8 -classpath /home/pmoy/.IdeaIC2019.2/config/plugins/Scala/lib/runners.jar:/home/pmoy/SourceCode/scala/cracking_the_coding_interview/out/production/cracking_the_coding_interview:/usr/share/scala/lib/scala-library.jar:/usr/share/scala/lib/scala-reflect.jar:/home/pmoy/Downloads/scalactic_sjs1.0.0-M8_2.13-3.0.8.jar:/home/pmoy/Downloads/scalatest_sjs1.0.0-M8_2.13-3.0.8.jar org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner -s HelloTest -C org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporter -showProgressMessages true
java.lang.NoClassDefFoundError: org/scalatest/tools/Runner
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
Caused by: java.lang.ClassNotFoundException: org.scalatest.tools.Runner
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```

**Comment by phrmoy** [comment]
This works fine as an SBT project.

**Comment by kell18** [comment]
Hi, Same problem here
