### ISSUE TITLE
java.lang.NoClassDefFoundError: org/scalatest/Matchers

### ISSUE THREAD

**Issue by mvillafuertem** [scalatest/scalatest#1734]
Hi I get this errorr before update to 3.1.0

https://circleci.com/gh/mvillafuertem/scala/59
```
[error] Caused by: java.lang.ClassNotFoundException: org.scalatest.Matchers
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:92)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:92)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
[error] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
[error] 	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
[error] 	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
[error] 	at java.base/java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
[error] 	at sbt.internal.ManagedClassLoader.findClass(ManagedClassLoader.java:92)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.loadSuiteClass(Framework.scala:404)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.suiteClass$lzycompute(Framework.scala:412)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.suiteClass(Framework.scala:412)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.accessible$lzycompute(Framework.scala:413)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.accessible(Framework.scala:413)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.shouldDiscover$lzycompute(Framework.scala:416)
[error] 	at org.scalatest.tools.Framework$ScalaTestTask.shouldDiscover(Framework.scala:416)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.$anonfun$tasks$2(Framework.scala:744)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.$anonfun$tasks$2$adapted(Framework.scala:742)
[error] 	at scala.collection.ArrayOps$WithFilter.map(ArrayOps.scala:90)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.tasks(Framework.scala:742)
[error] 	at sbt.TestRunner.tasks(TestFramework.scala:107)
[error] 	at sbt.TestFramework$.$anonfun$createTestTasks$4(TestFramework.scala:263)
[error] 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:277)
[error] 	at sbt.TestFramework$.$anonfun$createTestTasks$3(TestFramework.scala:263)
[error] 	at sbt.TestFramework$.$anonfun$createTestTasks$3$adapted(TestFramework.scala:260)
[error] 	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
[error] 	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:256)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:877)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:876)
[error] 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:256)
[error] 	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
[error] 	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
[error] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
[error] 	at sbt.TestFramework$.createTestTasks(TestFramework.scala:260)
[error] 	at sbt.TestFramework$.testTasks(TestFramework.scala:218)
[error] 	at sbt.Tests$.testTask(Tests.scala:237)
[error] 	at sbt.Tests$.apply(Tests.scala:216)
[error] 	at sbt.Defaults$.$anonfun$allTestGroupsTask$1(Defaults.scala:1178)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
[error] 	at scala.collection.immutable.List.foreach(List.scala:392)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
[error] 	at scala.collection.immutable.List.map(List.scala:298)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1158)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:894)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mrt181** [comment]
Can confirm this issue, rollback to `3.0.8` fixes the issue.

**Comment by cheeseng** [comment]
@mvillafuertem @mrt181 I took a look into this, I think the cause is in akka.actor.testkit.typed.scaladsl.ScalaTestWithActorTestKit, org.scalatest.Matchers is now a deprecated type alias in 3.1.0 (that requires a re-compile) but ScalaTestWithActorTestKit has a reference to org.scalatest.Matchers in the current version of class file, I think the solution will be for akka-actor-testkit-typed to update to ScalaTest 3.1.0 and re-compile https://github.com/akka/akka/blob/master/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ScalaTestWithActorTestKit.scala and release a new version.

**Comment by mrt181** [comment]
@cheeseng yes i am using actor-test-kit, thank you for the update

**Comment by mvillafuertem** [comment]
@cheeseng thank you for your research

**Comment by vreuter** [comment]
@mrt181 what's your `sbt` version? Rolling back to 3.0.8 didn't work for me with sbt 1.3.5, but using settings from an old project overcame this same issue for me. sbt 1.2.6 + scala 2.12.9 + scalacheck 1.14.0 + scalatest/scalactic 3.0.8 worked for me.

**Comment by mrt181** [comment]
@Vince works with sbt 1.3.5 and 1.3.6 for me

**Comment by vreuter** [comment]
Thanks for the reply @mrt181 . Interesting, I wonder what's peculiar about my configuration and/or use case. It's working now and I likely won't investigate further right away, but if so and anything interesting comes up maybe will write here for future reference.

**Comment by zallesov** [comment]
The issue comes from the akka-test-kit 2.6.x. it is still using scala-test 3.0.8 which imports the `org.scalatest.Matcher` instead of `org.scalatest.matchers.should.Matchers`. The workaround we went with is to redefine `ScalaTestWithActorTestKit` inside the project with the right imports

**Comment by vianel** [comment]
same here with scala-test 3.1.1 and akka 2.6.1

**Comment by Jacke** [comment]
Same. scalatest 3/1/1

**Comment by guizmaii** [comment]
If you have this problem and you're using Maven and the `scalatest-maven-plugin`, don't forger to disable `maven-surefire-plugin` as advised here: http://www.scalatest.org/user_guide/using_the_scalatest_maven_plugin

**Comment by Jacke** [comment]
Found the solution, scalatestplus-play using scalatest 3.0.8, I switched to the latest one and problem was solved.

**Comment by patriknw** [comment]
For the record, latest Akka 2.6.4 is using `org.scalatest.matchers.should.Matchers` and therefore requires ScalaTest 3.1.1 for the ScalaTestWithActorTestKit. If you for some reason have to stick to older ScalaTest 3.0.x you can implement your own ScalaTestWithActorTestKit rater easily by copy 2.6.1 version of [ScalaTestWithActorTestKit](https://github.com/akka/akka/blob/v2.6.1/akka-actor-testkit-typed/src/main/scala/akka/actor/testkit/typed/scaladsl/ScalaTestWithActorTestKit.scala).

**Comment by alexkamil** [comment]
If you are seeing this error: 
`java.lang.NoClassDefFoundError: org/scalatest/Matchers`
and are using PlaySpec in your tests, use this shim:
 
```
import org.scalatest._
import org.scalatest.matchers.must.Matchers
import org.scalatestplus.play.WsScalaTestClient
/**
  * Shim copied from https://github.com/playframework/scalatestplus-play/blob/master/module/src/main/scala/org/scalatestplus/play/PlaySpec.scala.
  *
  * As of 2/20/20, PlaySpec from scalatestplus-play is incompatible with scalatest 3.1.0.
  */
abstract class PlaySpec extends WordSpec with Matchers with OptionValues with WsScalaTestClient
```

scalatestplus-play has not yet released a new version using ScalaTest 3.1.X, hence the need for a shim. Otherwise, using scalatestplus-play will transitively pull in an outdated version of org/scalatest/Matchers.
