### ISSUE TITLE
StackOverflowError: null at org.scalactic.ObjectDiffer.difference

### ISSUE THREAD

**Issue by yanns** [scalatest/scalatest#1751]
We have a test that is sometimes failing with a huge stack trace starting with:

```
sbt.ForkMain$ForkError: sbt.ForkMain$ForkError: java.lang.StackOverflowError: null
	at java.lang.Class.getDeclaredFields(Class.java:1915)
	at org.scalactic.source.ObjectMeta$$anon$1.privFields$lzycompute(ObjectMeta.scala:36)
```

complete stacktrace at https://gist.github.com/yanns/6bcd708be2e7bbf73655449548036efb

**Comment by yanns** [comment]
I could not figure out what piece of code is producing that.
Any ideas / pointers would be welcome.

**Comment by yanns** [comment]
Some experiments are showing that this might be related to the JVM version.
Trying with the JVM 12 seems to fix the issue.
I'll update this issue if I can confirm that.
