### ISSUE TITLE
pendingUntilFixed doesn't handle async tests

### ISSUE THREAD

**Issue by mbbush** [scalatest/scalatest#1786]
pendingUntilFixed doesn't support async tests. 

```
package com.example

import org.scalatest.{AsyncWordSpec, Matchers}

import scala.concurrent.Future

class MyAsyncSpec extends AsyncWordSpec with Matchers {
  "pendingUntilFixed" should {
    "mark this test as pending" in pendingUntilFixed{
      Future{
        1 should be(2)
      }
    }
  }
}
```

This test fails with:
```
A block of code that was marked pendingUntilFixed did not throw an exception. Remove "pendingUntilFixed" and the curly braces to eliminate this failure.
ScalaTestFailureLocation: com.example.MyAsyncSpec$$anonfun$1$$anonfun$apply$mcV$sp$1 at (MyAsyncSpec.scala:9)
org.scalatest.exceptions.TestFailedException: A block of code that was marked pendingUntilFixed did not throw an exception. Remove "pendingUntilFixed" and the curly braces to eliminate this failure.
	at org.scalatest.Assertions$class.pendingUntilFixed(Assertions.scala:1327)
	at org.scalatest.AsyncWordSpec.pendingUntilFixed(AsyncWordSpec.scala:2294)
	at com.example.MyAsyncSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(MyAsyncSpec.scala:9)
	at com.example.MyAsyncSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(MyAsyncSpec.scala:9)
	at org.scalatest.AsyncWordSpecLike$class.transformToOutcomeParam$1(AsyncWordSpecLike.scala:136)
	at org.scalatest.AsyncWordSpecLike$$anonfun$org$scalatest$AsyncWordSpecLike$$registerTestToRun$2.apply(AsyncWordSpecLike.scala:137)
	at org.scalatest.AsyncWordSpecLike$$anonfun$org$scalatest$AsyncWordSpecLike$$registerTestToRun$2.apply(AsyncWordSpecLike.scala:137)
	at org.scalatest.AsyncTestSuite$$anonfun$transformToOutcome$1.apply(AsyncTestSuite.scala:240)
	at org.scalatest.AsyncTestSuite$$anonfun$transformToOutcome$1.apply(AsyncTestSuite.scala:239)
	at org.scalatest.AsyncWordSpecLike$$anon$1.apply(AsyncWordSpecLike.scala:1063)
	at org.scalatest.AsyncTestSuite$class.withFixture(AsyncTestSuite.scala:313)
	at org.scalatest.AsyncWordSpec.withFixture(AsyncWordSpec.scala:2294)
	at org.scalatest.AsyncWordSpecLike$class.invokeWithAsyncFixture$1(AsyncWordSpecLike.scala:1060)
	at org.scalatest.AsyncWordSpecLike$$anonfun$runTest$1.apply(AsyncWordSpecLike.scala:1074)
	at org.scalatest.AsyncWordSpecLike$$anonfun$runTest$1.apply(AsyncWordSpecLike.scala:1074)
	at org.scalatest.AsyncSuperEngine.runTestImpl(AsyncEngine.scala:292)
	at org.scalatest.AsyncWordSpecLike$class.runTest(AsyncWordSpecLike.scala:1074)
	at org.scalatest.AsyncWordSpec.runTest(AsyncWordSpec.scala:2294)
	at org.scalatest.AsyncWordSpecLike$$anonfun$runTests$1.apply(AsyncWordSpecLike.scala:1133)
	at org.scalatest.AsyncWordSpecLike$$anonfun$runTests$1.apply(AsyncWordSpecLike.scala:1133)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:434)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:419)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
	at org.scalatest.AsyncSuperEngine.org$scalatest$AsyncSuperEngine$$runTestsInBranch(AsyncEngine.scala:475)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:460)
	at org.scalatest.AsyncSuperEngine$$anonfun$traverseSubNodes$1$1.apply(AsyncEngine.scala:419)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at org.scalatest.AsyncSuperEngine.traverseSubNodes$1(AsyncEngine.scala:419)
	at org.scalatest.AsyncSuperEngine.org$scalatest$AsyncSuperEngine$$runTestsInBranch(AsyncEngine.scala:483)
	at org.scalatest.AsyncSuperEngine.runTestsImpl(AsyncEngine.scala:550)
	at org.scalatest.AsyncWordSpecLike$class.runTests(AsyncWordSpecLike.scala:1133)
	at org.scalatest.AsyncWordSpec.runTests(AsyncWordSpec.scala:2294)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.AsyncWordSpec.org$scalatest$AsyncWordSpecLike$$super$run(AsyncWordSpec.scala:2294)
	at org.scalatest.AsyncWordSpecLike$$anonfun$run$1.apply(AsyncWordSpecLike.scala:1178)
	at org.scalatest.AsyncWordSpecLike$$anonfun$run$1.apply(AsyncWordSpecLike.scala:1178)
	at org.scalatest.AsyncSuperEngine.runImpl(AsyncEngine.scala:620)
	at org.scalatest.AsyncWordSpecLike$class.run(AsyncWordSpecLike.scala:1178)
	at org.scalatest.AsyncWordSpec.run(AsyncWordSpec.scala:2294)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1346)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

Fixing this probably just requires writing a `def pendingUntilFixed(f: => Future[Assertion])`

**Comment by efgpinto** [comment]
Just faced this small issue today. I can try to contribute a fix if that's ok.
