### ISSUE TITLE
private val in case class

### ISSUE THREAD

**Issue by charpov** [scalatest/scalatest#1788]
The code below fails with an exception `class org.scalactic.source.ObjectMeta$$anon$1 cannot access a member with modifiers "private"`.  I know that case classes with private fields are frown upon, but are they illegal?

```scala
case class S(private val v: Vector[Int]) {
  override def toString: String = v.mkString
}

object S {
  def apply(x: Int*): S = S(x.toVector)
}

class SampleTests extends AnyFunSuite {

  test("test") {
    val p1 = S(1,2,3)
    val p2 = S(2,3,4)
    assert(p2 == p1)
  }
}
```

**Comment by bvenners** [comment]
That looks more like a bug, because you are not accessing the private member. Can you paste in the whole stack trace?

**Comment by charpov** [comment]
Here's the stack trace:
```
class org.scalactic.source.ObjectMeta$$anon$1 cannot access a member of class S with modifiers "private"
java.lang.IllegalAccessException: class org.scalactic.source.ObjectMeta$$anon$1 cannot access a member of class S with modifiers "private"
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
	at java.base/java.lang.reflect.Method.invoke(Method.java:559)
	at org.scalactic.source.ObjectMeta$$anon$1.value(ObjectMeta.scala:54)
	at org.scalactic.ObjectDiffer.$anonfun$difference$7(Differ.scala:233)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.Vector.flatMap(Vector.scala:119)
	at org.scalactic.ObjectDiffer.difference(Differ.scala:232)
	at org.scalactic.ObjectDiffer.difference$(Differ.scala:225)
	at org.scalactic.ObjectDiffer$.difference(Differ.scala:274)
	at org.scalactic.AnyDiffer.difference(Differ.scala:287)
	at org.scalactic.Prettifier.apply(Prettifier.scala:130)
	at org.scalactic.Prettifier.apply$(Prettifier.scala:129)
	at org.scalactic.Prettifier$$anon$2.apply(Prettifier.scala:185)
	at org.scalactic.BinaryMacroBool.prettyPair$lzycompute(Bool.scala:669)
	at org.scalactic.BinaryMacroBool.prettyPair(Bool.scala:662)
	at org.scalactic.BinaryMacroBool.analysis$lzycompute(Bool.scala:674)
	at org.scalactic.BinaryMacroBool.analysis(Bool.scala:672)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
	at Test.$anonfun$new$1(Test.scala:14)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.funsuite.AnyFunSuiteLike$$anon$1.apply(AnyFunSuiteLike.scala:189)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.funsuite.AnyFunSuite.withFixture(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.invokeWithFixture$1(AnyFunSuiteLike.scala:187)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTest$1(AnyFunSuiteLike.scala:199)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest(AnyFunSuiteLike.scala:199)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTest$(AnyFunSuiteLike.scala:181)
	at org.scalatest.funsuite.AnyFunSuite.runTest(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$runTests$1(AnyFunSuiteLike.scala:232)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests(AnyFunSuiteLike.scala:232)
	at org.scalatest.funsuite.AnyFunSuiteLike.runTests$(AnyFunSuiteLike.scala:231)
	at org.scalatest.funsuite.AnyFunSuite.runTests(AnyFunSuite.scala:1562)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.funsuite.AnyFunSuite.org$scalatest$funsuite$AnyFunSuiteLike$$super$run(AnyFunSuite.scala:1562)
	at org.scalatest.funsuite.AnyFunSuiteLike.$anonfun$run$1(AnyFunSuiteLike.scala:236)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funsuite.AnyFunSuiteLike.run(AnyFunSuiteLike.scala:236)
	at org.scalatest.funsuite.AnyFunSuiteLike.run$(AnyFunSuiteLike.scala:235)
	at org.scalatest.funsuite.AnyFunSuite.run(AnyFunSuite.scala:1562)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1320)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1314)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1314)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
```

**Comment by bvenners** [comment]
Ok looks like that's a bug in ScalaTest's differ, which is being used from the assert macro. I'll try later today to see if there's a workaround meanwhile.

**Comment by francisdb** [comment]
This pops up with play json
`cannot access a member of class play.api.libs.json.JsPath with modifiers "private"`

```scala
val JsSuccess(_, template) = TemplateFormat.reads(json)
template mustEqual testTemplate
```
(the result of TemplateFormat.reads(json) actually is JsSuccess but the equal check fails)

```
[info] - should allow getting a template *** FAILED ***
[info]   java.lang.IllegalAccessException: class org.scalactic.source.ObjectMeta$$anon$1 cannot access a member of class play.api.libs.json.JsPath with modifiers "private"
[info]   at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:559)
[info]   at org.scalactic.source.ObjectMeta$$anon$1.value(ObjectMeta.scala:54)
[info]   at org.scalactic.ObjectDiffer.$anonfun$difference$7(Differ.scala:233)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
[info]   at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
[info]   at org.scalactic.ObjectDiffer.difference(Differ.scala:232)
[info]   at org.scalactic.ObjectDiffer.difference$(Differ.scala:225)
```

**Comment by francisdb** [comment]
This pops up with play json
`cannot access a member of class play.api.libs.json.JsPath with modifiers "private"`

```scala
val JsSuccess(_, template) = TemplateFormat.reads(json)
template mustEqual testTemplate
```
(the result of TemplateFormat.reads(json) actually is JsSuccess but the equal check fails because we are comparing 2 different case class instances)

```
[info] - should allow getting a template *** FAILED ***
[info]   java.lang.IllegalAccessException: class org.scalactic.source.ObjectMeta$$anon$1 cannot access a member of class play.api.libs.json.JsPath with modifiers "private"
[info]   at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
[info]   at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
[info]   at java.base/java.lang.reflect.Method.invoke(Method.java:559)
[info]   at org.scalactic.source.ObjectMeta$$anon$1.value(ObjectMeta.scala:54)
[info]   at org.scalactic.ObjectDiffer.$anonfun$difference$7(Differ.scala:233)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
[info]   at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
[info]   at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
[info]   at org.scalactic.ObjectDiffer.difference(Differ.scala:232)
[info]   at org.scalactic.ObjectDiffer.difference$(Differ.scala:225)
```

**Comment by phucnh** [comment]
@bvenners

> Ok looks like that's a bug in ScalaTest's differ, which is being used from the assert macro. I'll try later today to see if there's a workaround meanwhile.

Hi, I'm trying to fix this issue. I think we can temporarily open the accessing to the private member of case class by `setAccessible`. Like as follows:

```scala
package org.scalactic.source

object ObjectMeta {
  def objectMetaUsingJavaReflection(v: Any): ObjectMeta =
    new ObjectMeta {
      ...
      def value(name: String): Any = {
        val fieldTry: Try[Method] = Try(v.getClass.getDeclaredMethod(name))
          .recoverWith {
            case e: NoSuchMethodException =>
              Try(v.getClass.getDeclaredMethod(name + "$mcI$sp"))
                .recoverWith {
                  case e: NoSuchMethodException =>
                    Failure(new IllegalArgumentException("'" + name + "' is not attribute for this instance."))
                }
          }

        fieldTry match {
          case Failure(e) => throw e
          case Success(field) =>
            try {
              field.invoke(v)
            } catch {
              case e: IllegalAccessException =>
                field.setAccessible(true)
                val value = field.invoke(v)
                field.setAccessible(false)
                value
            }
        }
      }  
}
```

But we have one problem here: we can access the `private val` inside the case class, it will make some noise on the diff analysis message. For example

```scala
case class Baz( s: String, private val i: Int) extends Parent { private val j = i }

val a = Baz("asdf", 5)
val b = Baz("asbdf", 6)

a shouldEqual b
```

Then, the following diff analysis message also contains `private val j`

```
DifferSpec$Baz(i: 5 -> 6, j: 5 -> 6, s: "as[]df" -> "as[b]df")
```

Should the `private val` inside case class be filtered? (And how 🤔 )
