### ISSUE TITLE
genRegularTests4 fails with NullPointerException

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#1852]
```
[error] (genRegularTests4 / Test / managedSources) java.lang.NullPointerException
[error] Total time: 1 s, completed Jul 24, 2020 3:12:36 PM
sbt:root> last genRegularTests4 / Test / managedSources
[error] java.lang.NullPointerException
[error] 	at scala.collection.mutable.ArrayOps$ofRef$.newBuilder$extension(ArrayOps.scala:202)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.newBuilder(ArrayOps.scala:198)
[error] 	at scala.collection.TraversableLike.partition(TraversableLike.scala:401)
[error] 	at scala.collection.TraversableLike.partition$(TraversableLike.scala:400)
[error] 	at scala.collection.mutable.ArrayOps$ofRef.partition(ArrayOps.scala:198)
[error] 	at GenRegularTestsBase.processJavaDir(GenRegularTestBase.scala:73)
[error] 	at GenRegularTestsBase.processJavaDir$(GenRegularTestBase.scala:71)
[error] 	at GenRegularTests4$.processJavaDir(GenRegularTests.scala:54)
[error] 	at GenRegularTestsBase.copyJavaDir(GenRegularTestBase.scala:92)
[error] 	at GenRegularTestsBase.copyJavaDir$(GenRegularTestBase.scala:91)
[error] 	at GenRegularTests4$.copyJavaDir(GenRegularTests.scala:54)
[error] 	at GenRegularTests4$.genJava(GenRegularTests.scala:65)
[error] 	at ScalatestBuild$.$anonfun$genRegularTests4$5(scalatest.scala:1208)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (genRegularTests4 / Test / managedSources) java.lang.NullPointerException
```

this came up in the Scala 2.13 community build (https://github.com/scala/community-build/pull/1172)

**Comment by SethTisue** [comment]
@cheeseng I tried this again with the current state of https://github.com/scalatest/scalatest/pull/1853 and instead of an NPE:

```
[error] /Users/tisue/scalatest/gentests/GenRegular4/target/scala-2.13/src_managed/test/org/scalatest/DeprecatedParallelTestExecutionSuiteTimeoutExamples.scala:42:44: not found: type EventHelpers
[error] trait DeprecatedSuiteTimeoutSuites extends EventHelpers {
[error]                                            ^
```

**Comment by SethTisue** [comment]
whereas in the context of the Scala 2.13 community build, it passes: scala/community-build#1190

I suppose there must be something order-dependent here — `genRegularTests4` fails if run first, but might pass if something else happens first — that kind of thing

**Comment by SethTisue** [comment]
there seems to be a similar problem now with `genTheyTests`. if I do `genTheyTests/test` in a fresh clone, I get:

```
[error] (genTheyTests / Test / managedSources) java.io.FileNotFoundException: jvm/scalatest-test/src/test/scala/org/scalatest/fixture/FlatSpecSpec.scala (No such file or directory)
```
