### ISSUE TITLE
Reporter completed abruptly with TryValues

### ISSUE THREAD

**Issue by seblm** [scalatest/scalatest#1883]
Since #1738 there is a regression:
given `SocketReporter` is registered (`-K host port`)
when any assertion failure is raised by `TryValues`
then `SocketReporter` completed abruptly

```
Exception in thread "Thread-37" java.io.WriteAbortedException: writing aborted; java.io.NotSerializableException: org.scalatest.TryValues$SuccessOrFailure
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1654)
...
Caused by: java.io.NotSerializableException: org.scalatest.TryValues$SuccessOrFailure
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
...
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 4),The Try on which success was invoked was not a Success; it was Failure(java.lang.Exception: failure).,MySpec,package.MySpec,Some(package.MySpec),My should works,should works,Vector(),Vector(),Some(org.scalatest.exceptions.TestFailedException: The Try on which success was invoked was not a Success; it was Failure(java.lang.Exception: failure).),Some(519),Some(IndentedText(- should works,should works,1)),Some(SeeStackDepthException),Some(package.MySpec),None,pool-1-thread-1-ScalaTest-running-MySpec,1598614861046).
java.io.NotSerializableException: org.scalatest.TryValues$SuccessOrFailure
```

**Comment by seblm** [comment]
Here is [a minimal project](https://github.com/seblm/try-values-not-serializable) that reproduce the defect.

**Comment by seblm** [comment]
For the record, #1738 introduces the regression onto [3.1.x branch](../tree/3.1.x) but it is actually #1878 that cherry-pick this change to [3.2.x branch](..).

**Comment by kpbochenek** [comment]
I am also getting something similar:
```
Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 2633),A timeout occurred waiting for a future to complete. Waited 450 milliseconds.,RedisSpec,scredis.RedisSpec,Some(scredis.RedisSpec),Auth when lazy clients are not initialized should authenticate all clients,authenticate all clients,Vector(),Vector(),Some(org.scalatest.concurrent.ScalaFutures$$anon$1$$anon$2: A timeout occurred waiting for a future to complete. Waited 450 milliseconds.),Some(481),Some(IndentedText(  - should authenticate all clients,should authenticate all clients,2)),Some(SeeStackDepthException),Some(scredis.RedisSpec),None,pool-1-thread-1-ScalaTest-running-RedisSpec,1599517093359).

java.io.NotSerializableException: org.scalatest.verbs.BehaveWord
```

Raw log: https://api.travis-ci.org/v3/job/725068175/log.txt

Should BehaveWord be also serializable in this case?

**Comment by kpbochenek** [comment]
Reproducable with:
```
        implicit val patienceConfig = PatienceConfig(timeout = Span(450, org.scalatest.time.Milliseconds))
        implicit val ec = ExecutionContext.Implicits.global
        Future {Thread.sleep(500); true}.futureValue should be (true)
```

**Comment by kpbochenek** [comment]
And all tests following this error fail, sometimes all just locks,  madness :(

**Comment by kpbochenek** [comment]
@seblm would it be possible to include test for Future in your PR? I would be very thankful :bowing_man:

**Comment by seblm** [comment]
> @seblm would it be possible to include test for Future in your PR? I would be very thankful 🙇‍♂️

Absolutely I will handle test for Future as well.
Fun fact I am experiencing same behavior and same stacks on other sbt projects too.

**Comment by seblm** [comment]
> @seblm would it be possible to include test for Future in your PR? I would be very thankful 🙇‍♂️

@kpbochenek please have a look at #1884 especially 27491f3514817fd7db6fe47129d39337a95b8308. Understanding why serialization failed was tricky. The fix is much invasive as I would. I hope to get feedback on this and ultimately being merged into next release?

**Comment by seblm** [comment]
> But! only running through sbt: `sbt 'testOnly package.MyTest'`, running from intellij works ...

You have correctly spotted the defect @kpbochenek.
I can guess you have configured your tests to run in a forked jvm through sbt. Then sbt automatically add a ScalaTest's `SocketReporter` in order to print test execution. Events emitted and received between these two processes are using good old jdk object serialization that just works fine unless it encounter non serializable classes. When this error occurs, stream is corrupt until the end of test execution.

**Comment by kpbochenek** [comment]
Yes, forked set to true :+1: 

It should happen for a lot of projects, I am confused why there is no more fuss about this issue Oo
Do people tests always pass? :P

**Comment by DavidPerezIngeniero** [comment]
And what is the recommended workaround when `forked` is needed?

**Comment by bvenners** [comment]
@DavidPerezIngeniero This should be solved now in 3.2. Are you experiencing it? If so, in what version?

**Comment by seblm** [comment]
@DavidPerezIngeniero to be a little more precise this should be solved since [3.2.3](https://github.com/scalatest/scalatest/releases/tag/release-3.2.3).

**Comment by DavidPerezIngeniero** [comment]
Thanks, that's good news!

**Comment by DavidPerezIngeniero** [comment]
I'm using ScalaTest 3.2.9, and when a test throws a org.python.PyException (from Jython), a non-serializable Exception, then I receive all this terrible noise for every test afterwards:

```
java.io.NotSerializableException: org.python.proxies.info_editor$InfoEditor$13
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1379)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.scalatest.tools.SocketReporter.apply(SocketReporter.scala:31)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10(DispatchReporter.scala:249)
	at org.scalatest.DispatchReporter$Propagator.$anonfun$run$10$adapted(DispatchReporter.scala:248)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:248)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by seblm** [comment]
> Is there any workaround?
You can avoid ScalaTest using `SocketReporter` by telling sbt not to fork a new jvm when running tests but it can’t be always feasible.

> If an exception is no serializable, it coud just extract the class name of the exception and the message.
That’s a great idea.

> Should I open another issue?
Yes sure I will propose a new fix accordingly.
