### ISSUE TITLE
Can't run JUnit suites on 3.2.2

### ISSUE THREAD

**Issue by gabrielrussoc** [scalatest/scalatest#1971]
I have the following JUnit suite:

```
import org.junit.Assert;
import org.junit.Test;

public class ExampleSuite extends Assert {

    @Test
    public void success(){
    }

    @Test
    public void failure(){
	int x = 1/0;
    }
}
```

If I try to run it as `org.scalatest.tools.Runner.main(-j, ExampleSuite, -u, report, -oDF)`, following the [using the runner](https://www.scalatest.org/user_guide/using_the_runner) docs, it fails with:

```
*** RUN ABORTED *** (19 milliseconds)
  java.lang.ClassNotFoundException: org.scalatest.junit.JUnitWrapperSuite
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1208)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1480)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
  at org.scalatest.tools.Runner$.main(Runner.scala:775)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.base/java.lang.reflect.Method.invoke(Method.java:564)
  at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
  at java.base/java.lang.Thread.run(Thread.java:832)
```
  
I believe the JUnitWrapperSuite class was moved to [scalatestplus-junit](https://github.com/scalatest/scalatestplus-junit) but the runner was not updated accordingly.

Full repro on https://github.com/gabrielrussoc/scalatest-junit-xml/tree/3.2.2

**Comment by cheeseng** [comment]
It seems to me that the version of scalatest+junit is not right, can you try 3.2.2.0?

**Comment by gabrielrussoc** [comment]
```
[ERROR] Failed to execute goal on project scalatest-junit-xml: Could not resolve dependencies for project com.databricks:scalatest-junit-xml:jar:1: Could not find artifact org.scalatestplus:scalatestplus-junit_2.13:jar:3.2.2.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

**Comment by cheeseng** [comment]
@gabrielrussoc It should be here: 

https://mvnrepository.com/artifact/org.scalatestplus/junit-4-13

You may want to refer to the maven config in README here: 

https://github.com/scalatest/scalatestplus-junit

Note: Latest version for ScalaTest is 3.2.5 and ScalaTest+JUnit is 3.2.5.0.

**Comment by cheeseng** [comment]
@gabrielrussoc  Sorry I just realize there's a problem for maven config on the README page, it should be something like this: 

```
<!-- https://mvnrepository.com/artifact/org.scalatestplus/junit-4-13 -->
<dependency>
    <groupId>org.scalatestplus</groupId>
    <artifactId>junit-4-13_2.13</artifactId>
    <version>3.2.5.0</version>
    <scope>test</scope>
</dependency>
```

I'll rectify the README.

**Comment by gabrielrussoc** [comment]
I believe the problem still exists with these changes:

```
*** RUN ABORTED *** (26 milliseconds)
  java.lang.ClassNotFoundException: org.scalatest.junit.JUnitWrapperSuite
  at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:435)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

with the following pom:
```
<dependencies>
    <dependency>
      <groupId>org.scalactic</groupId>
      <artifactId>scalactic_2.13</artifactId>
      <version>3.2.5</version>
    </dependency>
    <dependency>
      <groupId>org.scalatest</groupId>
      <artifactId>scalatest_2.13</artifactId>
      <version>3.2.5</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
    </dependency>
    <dependency>
      <groupId>org.scalatestplus</groupId>
      <artifactId>junit-4-13_2.13</artifactId>
      <version>3.2.5.0</version>
    </dependency>
  </dependencies>
```

full repro here https://github.com/gabrielrussoc/scalatest-junit-xml/tree/3.2.5

**Comment by cheeseng** [comment]
@gabrielrussoc Sorry for the delay, finally able to work on this, to confirm this is a bug in Runner and I submitted the following PR: 

https://github.com/scalatest/scalatest/pull/1974

Hopefully it can be merged and release 3.2.6 asap to include the fix.

Cheers.

**Comment by gabrielrussoc** [comment]
@cheeseng thanks for the quick fix! Did you get a chance to try the issue reported on #1972 on top of your changes?
