### ISSUE TITLE
NPE in assert macro in Scala 3 REPL

### ISSUE THREAD

**Issue by bvenners** [scalatest/scalatest#1998]
Hi Chee Seng,

We are throwing an NPE in the Scala 3 REPL with this session (that has ScalaTest and Scalactic on the path):

```
scala> val x = 1
val x: Int = 1

scala> val y = 2
val y: Int = 2

scala> org.scalatest.Assertions.assert(x == y)                                                              
1 |org.scalatest.Assertions.assert(x == y)
  |                                       ^
  |  Exception occurred while executing macro expansion.
  |  java.lang.NullPointerException
  |  	at org.scalactic.source.Position$.genPosition(Position.scala:73)
  |  	at org.scalactic.source.Position$.inline$genPosition(Position.scala:70)
  |
  | This location contains code that was inlined from rs$line$3:1

```

**Comment by bvenners** [comment]
@cheeseng by the way this one we should fix in 3.2.x-new

**Comment by cheeseng** [comment]
@bvenners Fyi I submitted the following to fix this: 

https://github.com/scalatest/scalatest/pull/2001

**Comment by bvenners** [comment]
Merged. Tnx.
