### ISSUE TITLE
Type check passes incorrectly with two F-bounded type parameters

### ISSUE THREAD

**Issue by kierendavies** [scalatest/scalatest#2099]
The test following in the following code fails, when it should pass.

```scala
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

trait LeftSock[L <: LeftSock[L, R], R <: RightSock[L, R]]
trait RightSock[L <: LeftSock[L, R], R <: RightSock[L, R]]

class TypeCheckTest extends AnyFlatSpec with Matchers {
  "This code" should "fail type check" in {
    "trait MyLeftSock extends LeftSock[MyLeftSock, MyLeftSock]" shouldNot typeCheck
  }
}
```

```
$ sbt test
...
[info] TypeCheckTest:
[info] This code
[info] - should fail type check *** FAILED ***
[info]   Expected a type error, but got none for code: trait MyLeftSock extends LeftSock[MyLeftSock, MyLeftSock] (TypeCheckTest.scala:9)
...
```

Replacing the matcher line with the code from the string causes compilation to fail with a type error.

```
$ sbt test
...
[error] .../src/test/scala/TypeCheckTest.scala:9:30: type arguments [MyLeftSock,MyLeftSock] do not conform to trait LeftSock's type parameter bounds [L <: LeftSock[L,R],R <: RightSock[L,R]]
[error]     trait MyLeftSock extends LeftSock[MyLeftSock, MyLeftSock]
[error]                              ^
...
```

Scala 2.13.7, ScalaTest 3.2.11

**Comment by cheeseng** [comment]
@kierendavies It seems like the typeCheck call here is happy about your code: 

https://github.com/scalatest/scalatest/blob/3.2.x-new/jvm/core/src/main/scala/org/scalatest/CompileMacro.scala#L599

The checking for your case probably comes in different phase of the compiler, @SethTisue would you mind to confirm the compiler phase that's does the checking for this case?

**Comment by kierendavies** [comment]
I should have said when I created the issue: the same code with `shouldNot compile` also fails because the matcher thinks it compiles, so I don't think it's (only) about the check happening at a different compilation phase.

**Comment by cheeseng** [comment]
@kierendavies Actually the 'shouldNot compile' also just use the typeCheck, there's no better option afaik in the macro unless we switch to call the full compiler, perhaps for the 'compile' we should do that.

**Comment by SethTisue** [comment]
> @SethTisue would you mind to confirm the compiler phase that's does the checking for this case?

Running the compiler with `-Xprompt` confirms that it happens in a later phase, namely refchecks:

```
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.scala$tools$nsc$typechecker$RefChecks$RefCheckTransformer$$checkBounds(RefChecks.scala:1251)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.checkTypeRef(RefChecks.scala:1465)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.apply(RefChecks.scala:1453)
	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer$RefCheckTypeMap$.check(RefChecks.scala:1435)
```

running `scalac -Xshow-phases` shows the order of phases:

```
~ % scalac -Xshow-phases                                                                   [main|✔]
    phase name  id  description
    ----------  --  -----------
        parser   1  parse source into ASTs, perform simple desugaring
         namer   2  resolve names, attach symbols to named trees
packageobjects   3  load package objects
         typer   4  the meat and potatoes: type the trees
superaccessors   5  add super accessors in traits and nested classes
    extmethods   6  add extension methods for inline classes
       pickler   7  serialize symbol tables
     refchecks   8  reference/override checking, translate nested objects
...
```
