### ISSUE TITLE
Add option to disable stacktrace omission

### ISSUE THREAD

**Issue by tribbloid** [scalatest/scalatest#2145]
When running scalatest in maven, one common problem plaguing the build is the error message:

(Using scalatest 3.1.x as an example)

```
xxx.Suite *** ABORTED ***
  java.lang.RuntimeException: Unable to load a Suite class that was discovered in the runpath: com.schedule1.datapassports.spark.udf.DPIDSuite
  at org.scalatest.tools.DiscoverySuite$.getSuiteInstance(DiscoverySuite.scala:81)
  at org.scalatest.tools.DiscoverySuite.$anonfun$nestedSuites$1(DiscoverySuite.scala:38)
  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
  at scala.collection.Iterator.foreach(Iterator.scala:943)
  at scala.collection.Iterator.foreach$(Iterator.scala:943)
  at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  at scala.collection.IterableLike.foreach(IterableLike.scala:74)
  at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
  at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
  at scala.collection.TraversableLike.map(TraversableLike.scala:285)
  ...
DiscoverySuite:
DiscoverySuite:
```

This error message can be traced to the following sourcecode:

```
  private[scalatest] def getSuiteInstance(suiteClassName: String, loader: ClassLoader): Suite = {
    try {
      val clazz = loader.loadClass(suiteClassName)
      val wrapWithAnnotation = clazz.getAnnotation(classOf[WrapWith])
      if (wrapWithAnnotation == null)
        clazz.newInstance.asInstanceOf[Suite]
      else {
        val suiteClazz = wrapWithAnnotation.value
        val constructorList = suiteClazz.getDeclaredConstructors()
        val constructor = constructorList.find { c => 
          val types = c.getParameterTypes
          types.length == 1 && types(0) == classOf[java.lang.Class[_]]
        }
        constructor.get.newInstance(clazz).asInstanceOf[Suite]
      }
    }
    catch {
      case t: Throwable => { // TODO: Maybe include the e.getClass.getName and the message for e in the message cannotLoadDiscoveredSuite, because Jess had the problem
                             // That gradle cut off the stack trace so she couldn't see the cause.
        val msg = Resources.cannotLoadDiscoveredSuite(suiteClassName)
        new DeferredAbortedSuite(suiteClassName, suiteClassName, new RuntimeException(msg, t))
      }
    }
  }
```

the `RuntimeException` should always be accompanied by a cause, but this information is omitted making the test error impossible to fix.

The following comment:

```
// TODO: Maybe include the e.getClass.getName and the message for e in the message cannotLoadDiscoveredSuite, because Jess had the problem
                             // That gradle cut off the stack trace so she couldn't see the cause.
```

Shows the exact same symptom that is blocking the build.

We should stop omitting stacktrace, or at least make it an option that can be optionally disabled

**Comment by cheeseng** [comment]
@tribbloid Will -oF helps to print out the full stack trace?

**Comment by tribbloid** [comment]
sorry for the delay, haven't tried it so far but will do it in the weekend.
