### ISSUE TITLE
what's the right way to use scalatest with scalatestplus.junit5?

### ISSUE THREAD

**Issue by xinzhao-db** [scalatest/scalatest#2309]
According to https://www.scalatest.org/plus/junit5/versions, scalatest v3.2.16 should work with scalatestplus-junit5 v3.16.0

However, in scalatest v3.2.16, it [explicitly looks for](https://github.com/scalatest/scalatest/blob/release-3.2.16/jvm/core/src/main/scala/org/scalatest/tools/Runner.scala#L1040) `org.scalatestplus.junit.JUnitWrapperSuite` which only exist in [scalatest-junit](https://github.com/scalatest/scalatestplus-junit/tree/main/src/main/scala/org/scalatestplus/junit) but not in [scalatest-junit5](https://github.com/scalatest/scalatestplus-junit5/tree/release-3.2.16.0-for-junit-5.9/src/main/scala/org/scalatestplus/junit5)

Hence, I keep getting errors as below. Is it a bug or am I using in a wrong way? I am using bazel hence I invoke runner programmatically, maybe for junit5 the entry point is different? Thanks!

```java.lang.ClassNotFoundException: org.scalatestplus.junit.JUnitWrapperSuite
  at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
  at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
  at org.scalatest.tools.Runner$.loadJUnitWrapperClass(Runner.scala:1040)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1210)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:992)
  at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:970)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1481)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:970)
  at org.scalatest.tools.Runner$.run(Runner.scala:798)```

**Comment by cheeseng** [comment]
@xinzhao-db  -j should be used only for JUnit 4 classes, run using the wrapper approach.  The Runner docs does not explicitly says JUnit 4, sorry for the confusion.  Using the current version of of scalatest+junit5, there's no wrapper approach anymore.  You may extend JUnitSuite or mixin in JUnitSuiteLike into your JUnit 5 classes which should make ScalaTest Runner to run them.  Alternatively, with the present of scalatest+junit5 classes on the classpath, JUnit 5's runner should be able to discover ScalaTest's suite classes and run them.

I'll update the documentation for -j to explicitly says it is for JUnit 4 classes, sorry again for the confusion.

**Comment by xinzhao-db** [comment]
@cheeseng Thanks for the help! It's working after I extending JUnitSuite and use `-s`.
