### ISSUE TITLE
ScalaTest all release jar files are empty and file size is 1kb

### ISSUE THREAD

**Issue by wanaright10** [scalatest/scalatest#2324]
Please help check why all version of release artifact jar files are empty, and the size only 1kb? 
Also maven repo files are empty as well, I can't compile my test codes.
ex this version:
https://repo1.maven.org/maven2/org/scalatest/scalatest_3/3.2.10/

**Comment by cheeseng** [comment]
@wanaright10 This is intended, it only contains dependencies to other modules, if you are looking for jar file that contains all the scalatest, use scalatest-app instead: 

https://repo1.maven.org/maven2/org/scalatest/scalatest-app_3/3.2.18/

**Comment by wanaright10** [comment]
still missing some other classes:
```
java.lang.NoClassDefFoundError: scala/xml/MetaData
        at org.scalatest.tools.ReporterFactory.createJunitXmlReporter(ReporterFactory.scala:221)
        at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:242)
        at org.scalatest.tools.ReporterFactory.$anonfun$createReportersFromConfigurations$1(ReporterFactory.scala:254)
        at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
        at scala.collection.immutable.List.prependedAll(List.scala:156)
        at scala.collection.immutable.List$.from(List.scala:684)
        at scala.collection.immutable.List$.from(List.scala:681)
        at scala.collection.SeqFactory$Delegate.from(Factory.scala:306)
        at scala.collection.immutable.Seq$.from(Seq.scala:42)
        at scala.collection.immutable.Seq$.from(Seq.scala:39)
        at scala.collection.IterableOps.map(Iterable.scala:682)
        at scala.collection.IterableOps.map$(Iterable.scala:682)
        at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
```

em.... I don't want add dependencies one by one ... hople someone can help fix the maven repo issue...

**Comment by cheeseng** [comment]
Nothing wrong with the repo, you can either use a build tool with dependency management or if you are running with java/scala command you;ll need to include scala-xml jar in your classpath, see: 

https://www.scalatest.org/user_guide/using_the_runner
