### ISSUE TITLE
Report reminders not working with the standard reporter

### ISSUE THREAD

**Issue by Ivan091** [scalatest/scalatest#2348]
[Link](https://github.com/Ivan091/scalatest-reporter-reminder) to the repo to reproduce the issue

Consider the following setup: 
scala: 3.4.0
scalatest: 3.2.18

```scala
final class Test extends AnyWordSpec with Matchers {

  "successful test 1" in {
    1 shouldBe 1
  }

  "successful test 2" in {
    1 shouldBe 1
  }

  "failing test 1" in {
    throw new RuntimeException("Failing test 1 is failing")
  }

  "failing test 2" in {
    throw new RuntimeException("Failing test 2 is failing ")
  }

  "successful test 3" in {
    1 shouldBe 1
  }
}
```

If the tests are run as the following:
```
testOnly  -- -oI
```
I expect it to print all the failing tests with the stack traces after all the tests are finished
But I see this instead:
```
[info] Run completed in 465 milliseconds.
[info] Total number of tests run: 5                                                                                                                                                                        
[info] Suites: completed 1, aborted 0                                                                                                                                                                      
[info] Tests: succeeded 3, failed 2, canceled 0, ignored 0, pending 0                                                                                                                                      
[info] *** 2 TESTS FAILED ***                                                                                                                                                                              
[error] Failed tests:                                                                                                                                                                                      
[error]         com.meineliebe.Test                                                                                                                                                                        
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful                                                                                                                                     
[error] Total time: 1 s, completed 31 Oct 2024, 11:02:23 
```
It just prints the class where the red tests are located which is not really convenient for debugging

As a workaround I've found It works with the error reporter:
```
testOnly  -- -eI
```
```
Run completed in 478 milliseconds.
Total number of tests run: 5
Suites: completed 1, aborted 0
Tests: succeeded 3, failed 2, canceled 0, ignored 0, pending 0
*** 2 TESTS FAILED ***
Test:

- failing test 1 *** FAILED ***
  java.lang.RuntimeException: Failing test 1 is failing
  at com.meineliebe.Test.f$proxy3$1(Test.scala:17)
  at com.meineliebe.Test.$init$$$anonfun$3(Test.scala:16)
  at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:21)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  ...
Test:

- failing test 2 *** FAILED ***
  java.lang.RuntimeException: Failing test 2 is failing
  at com.meineliebe.Test.f$proxy4$1(Test.scala:21)
  at com.meineliebe.Test.$init$$$anonfun$4(Test.scala:20)
  at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:21)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  ...
[info] Run completed in 478 milliseconds.
[info] Total number of tests run: 5                                                                                                                                                                        
[info] Suites: completed 1, aborted 0                                                                                                                                                                      
[info] Tests: succeeded 3, failed 2, canceled 0, ignored 0, pending 0                                                                                                                                      
[info] *** 2 TESTS FAILED ***                                                                                                                                                                              
[error] Failed tests:                                                                                                                                                                                      
[error]         com.meineliebe.Test                                                                                                                                                                        
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful                                                                                                                                     
[error] Total time: 1 s, completed 31 Oct 2024, 11:04:59
```
Though, some information is duplicated but I can see failing test name and the stack trace so I don't have to scroll up for this

I bet it's a bug, the doc clearly states the modifiers: ```I T G``` can be used with the standard output ```-o```

P.S. It looks like the I param is not working as intended even with the ```-e```, the doc states it should cut the stack traces off, but it seems it shortens them

**Comment by cheeseng** [comment]
@Ivan091 Hmm, weird, I cloned your example repo to try reproduce the problem, but when I ran it using the way you described I got: 

```
(base) cheeseng@cheeseng-RAVEN:~/git/artima/scalatest-reporter-reminder$ sbt
[info] welcome to sbt 1.9.9 (Oracle Corporation Java 23.0.1)
[info] loading settings for project scalatest-reporter-reminder-build from plugins.sbt ...
[info] loading project definition from /home/cheeseng/git/artima/scalatest-reporter-reminder/project
[info] loading settings for project scalatest-reporter-reminder from build.sbt ...
[info] set current project to scala-with-cats (in build file:/home/cheeseng/git/artima/scalatest-reporter-reminder/)
[info] sbt server started at local:///home/cheeseng/.sbt/1.0/server/c48ba5cee5eb1ee437ce/sock
[info] started sbt server
sbt:scala-with-cats> testOnly  -- -oI
> 
> 
[info] compiling 1 Scala source to /home/cheeseng/git/artima/scalatest-reporter-reminder/target/scala-3.4.0/test-classes ...
[info] Test:
[info] - successful test 1
[info] - successful test 2
[info] - failing test 1 *** FAILED ***
[info]   java.lang.RuntimeException: Failing test 1 is failing
[info]   at com.meineliebe.Test.f$proxy3$1(Test.scala:17)
[info]   at com.meineliebe.Test.$init$$$anonfun$3(Test.scala:16)
[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   ...
[info] - failing test 2 *** FAILED ***
[info]   java.lang.RuntimeException: Failing test 2 is failing
[info]   at com.meineliebe.Test.f$proxy4$1(Test.scala:21)
[info]   at com.meineliebe.Test.$init$$$anonfun$4(Test.scala:20)
[info]   at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:21)
[info]   at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   ...
[info] - successful test 3
[info] Run completed in 800 milliseconds.
[info] Total number of tests run: 5
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 3, failed 2, canceled 0, ignored 0, pending 0
[info] *** 2 TESTS FAILED ***
[error] Failed tests:
[error] 	com.meineliebe.Test
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed Nov 1, 2024, 9:48:04 PM
```

I am not sure what else is different that can cause the problem.

**Comment by Ivan091** [comment]
@cheeseng I've managed to reproduce it :)
You see the failed tests with stack traces among other successful tests
When you run it with `testOnly  -- -fI` (in the issue I mentioned the error reporter `-e` but with file reporter `-f` it works as well) you should get:
```
Run starting. Expected test count is: 0
Test:
- successful test 1
- successful test 2
- failing test 1 *** FAILED ***
  java.lang.RuntimeException: Failing test 1 is failing
  at com.meineliebe.Test.f$proxy3$1(Test.scala:17)
  at com.meineliebe.Test.$init$$$anonfun$3(Test.scala:16)
  at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:21)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  ...
- failing test 2 *** FAILED ***
  java.lang.RuntimeException: Failing test 2 is failing
  at com.meineliebe.Test.f$proxy4$1(Test.scala:21)
  at com.meineliebe.Test.$init$$$anonfun$4(Test.scala:20)
  at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:21)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  ...
- successful test 3
Run completed in 520 milliseconds.
Total number of tests run: 5
Suites: completed 1, aborted 0
Tests: succeeded 3, failed 2, canceled 0, ignored 0, pending 0
*** 2 TESTS FAILED ***
Test:

- failing test 1 *** FAILED ***
  java.lang.RuntimeException: Failing test 1 is failing
  at com.meineliebe.Test.f$proxy3$1(Test.scala:17)
  at com.meineliebe.Test.$init$$$anonfun$3(Test.scala:16)
  at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:21)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  ...
Test:

- failing test 2 *** FAILED ***
  java.lang.RuntimeException: Failing test 2 is failing
  at com.meineliebe.Test.f$proxy4$1(Test.scala:21)
  at com.meineliebe.Test.$init$$$anonfun$4(Test.scala:20)
  at org.scalatest.Transformer.apply$$anonfun$1(Transformer.scala:22)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:31)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:21)
  at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1118)
  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
  ...
```

At the bottom, you can find the summary of all failed tests (after `*** 2 TESTS FAILED ***`)
