### ISSUE TITLE
scalatestplus-junit engine broken with NoSuchMethodException

### ISSUE THREAD

**Issue by tribbloid** [scalatest/scalatest#2351]
When I use the plugin by following this instruction:

https://www.scalatest.org/plus/junit5

```
        testRuntimeOnly("org.junit.platform:junit-platform-engine:1.11.3")
        testRuntimeOnly("org.junit.platform:junit-platform-launcher:1.11.3")
        testRuntimeOnly("org.scalatestplus:junit-5-11_3:3.2.19.0")
```

I got the following error

```

TestEngine with ID 'scalatest' failed to execute tests
org.junit.platform.commons.JUnitException: TestEngine with ID 'scalatest' failed to execute tests
Caused by: java.lang.NoSuchMethodError: 'org.scalatest.events.TestStarting org.scalatest.events.TestStarting$.unapply(org.scalatest.events.TestStarting)'
	at org.scalatestplus.junit5.EngineExecutionListenerReporter.apply(EngineExecutionListenerReporter.scala:55)
	at org.scalatest.WrapperCatchReporter.doApply(CatchReporter.scala:70)
	at org.scalatest.CatchReporter.apply(CatchReporter.scala:36)
	at org.scalatest.CatchReporter.apply$(CatchReporter.scala:34)
	at org.scalatest.WrapperCatchReporter.apply(CatchReporter.scala:63)
	at org.scalatest.Suite$.reportTestStarting(Suite.scala:1650)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:267)
	at org.scalatest.funspec.AnyFunSpecLike.runTest(AnyFunSpecLike.scala:531)
	at org.scalatest.funspec.AnyFunSpecLike.runTest$(AnyFunSpecLike.scala:513)
	at org.scalatest.funspec.AnyFunSpec.runTest(AnyFunSpec.scala:1632)
	at org.scalatest.funspec.AnyFunSpecLike.$anonfun$runTests$1(AnyFunSpecLike.scala:564)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funspec.AnyFunSpecLike.runTests(AnyFunSpecLike.scala:564)
	at org.scalatest.funspec.AnyFunSpecLike.runTests$(AnyFunSpecLike.scala:563)
	at org.scalatest.funspec.AnyFunSpec.runTests(AnyFunSpec.scala:1632)
	at org.scalatest.Suite.run(Suite.scala:1114)
	at org.scalatest.Suite.run$(Suite.scala:1096)
	at org.scalatest.funspec.AnyFunSpec.org$scalatest$funspec$AnyFunSpecLike$$super$run(AnyFunSpec.scala:1632)
	at org.scalatest.funspec.AnyFunSpecLike.$anonfun$run$1(AnyFunSpecLike.scala:568)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funspec.AnyFunSpecLike.run(AnyFunSpecLike.scala:568)
	at org.scalatest.funspec.AnyFunSpecLike.run$(AnyFunSpecLike.scala:567)
	at org.scalatest.funspec.AnyFunSpec.run(AnyFunSpec.scala:1632)
	at org.scalatestplus.junit5.ScalaTestEngine.execute$$anonfun$1(ScalaTestEngine.scala:324)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at org.scalatestplus.junit5.ScalaTestEngine.execute(ScalaTestEngine.scala:253)


'org.scalatest.events.TestStarting org.scalatest.events.TestStarting$.unapply(org.scalatest.events.TestStarting)'
java.lang.NoSuchMethodError: 'org.scalatest.events.TestStarting org.scalatest.events.TestStarting$.unapply(org.scalatest.events.TestStarting)'
	at org.scalatestplus.junit5.EngineExecutionListenerReporter.apply(EngineExecutionListenerReporter.scala:55)
	at org.scalatest.WrapperCatchReporter.doApply(CatchReporter.scala:70)
	at org.scalatest.CatchReporter.apply(CatchReporter.scala:36)
	at org.scalatest.CatchReporter.apply$(CatchReporter.scala:34)
	at org.scalatest.WrapperCatchReporter.apply(CatchReporter.scala:63)
	at org.scalatest.Suite$.reportTestStarting(Suite.scala:1650)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:267)
	at org.scalatest.funspec.AnyFunSpecLike.runTest(AnyFunSpecLike.scala:531)
	at org.scalatest.funspec.AnyFunSpecLike.runTest$(AnyFunSpecLike.scala:513)
	at org.scalatest.funspec.AnyFunSpec.runTest(AnyFunSpec.scala:1632)
	at org.scalatest.funspec.AnyFunSpecLike.$anonfun$runTests$1(AnyFunSpecLike.scala:564)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:334)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.funspec.AnyFunSpecLike.runTests(AnyFunSpecLike.scala:564)
	at org.scalatest.funspec.AnyFunSpecLike.runTests$(AnyFunSpecLike.scala:563)
	at org.scalatest.funspec.AnyFunSpec.runTests(AnyFunSpec.scala:1632)
	at org.scalatest.Suite.run(Suite.scala:1114)
	at org.scalatest.Suite.run$(Suite.scala:1096)
	at org.scalatest.funspec.AnyFunSpec.org$scalatest$funspec$AnyFunSpecLike$$super$run(AnyFunSpec.scala:1632)
	at org.scalatest.funspec.AnyFunSpecLike.$anonfun$run$1(AnyFunSpecLike.scala:568)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.funspec.AnyFunSpecLike.run(AnyFunSpecLike.scala:568)
	at org.scalatest.funspec.AnyFunSpecLike.run$(AnyFunSpecLike.scala:567)
	at org.scalatest.funspec.AnyFunSpec.run(AnyFunSpec.scala:1632)
	at org.scalatestplus.junit5.ScalaTestEngine.execute$$anonfun$1(ScalaTestEngine.scala:324)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:619)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:617)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:935)
	at org.scalatestplus.junit5.ScalaTestEngine.execute(ScalaTestEngine.scala:253)

```

When I revert to use `co.helmethair:scalatest-junit-runner:0.2.0`, the error disappear

**Comment by cheeseng** [comment]
@tribbloid Hmm, perhaps you are missing `testImplementation "org.scalatest:scalatest_3:3.2.19"` ?  You may want to refer to latest examples that I just updated here: 

https://github.com/scalatest/scalatestplus-junit5/tree/main/examples

Hope the above can help.

Cheers.
