### ISSUE TITLE
Cannot run akka tests inside Intellij

### ISSUE THREAD

**Issue by vasily-kirichenko** [scalatest/scalatest#373]
When I try to run this akka test (copied from http://doc.akka.io/docs/akka/2.3.5/scala/testing.html) from Intellij IDEA:

```scala
import akka.actor.ActorSystem
import akka.testkit.{TestActors, ImplicitSender, TestKit}
import org.scalatest.{BeforeAndAfterAll, Matchers, WordSpecLike}

class RoundRobinTest(_system: ActorSystem) extends TestKit(_system) with ImplicitSender
  with WordSpecLike with Matchers with BeforeAndAfterAll {
  def this() = this(ActorSystem("RoundRobinTest"))
  override def afterAll() = TestKit.shutdownActorSystem(system)

  "An Echo actor" must {
    "send back messages unchanged" in {
      val echo = system.actorOf(TestActors.echoActorProps)
      echo ! "hello!"
      expectMsg("hello!")
    }
  }
}
```
I get the following error:

```
"C:\Program Files\Java\jdk1.8.0_11\bin\java" -Didea.launcher.port=7536 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 13.1.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Users\kot\.IdeaIC13\config\plugins\Scala\lib\scala-plugin-runners.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_11\jre\lib\ext\zipfs.jar;L:\git\scala\AkkaRouterTest\project\target\idea-classes;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\sbt-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\task-system-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\lib\jline.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\process-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\tracking-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\control-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\lib\scala-library.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\compiler-integration-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\actions-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\cache-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\relation-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\ivy-2.3.0.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\logic-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\classfile-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\collections-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\xsbti\interface-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\persist-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\incremental-compiler-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\compiler-ivy-integration-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\lib\jansi.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\jsch-0.1.46.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\run-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\jline-2.11.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\tasks-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\scala-reflect-2.10.4.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\testing-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\compile-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\launcher-interface-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\lib\scala-reflect.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\api-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\test-agent-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\main-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\main-settings-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\ivy-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\completion-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\lib\scala-compiler.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\command-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\sbinary_2.10-0.4.2.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\apply-macro-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\classpath-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\cross-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\logging-0.13.5.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\test-interface-1.0.jar;C:\Users\kot\.sbt\boot\scala-2.10.4\org.scala-sbt\sbt\0.13.5\io-0.13.5.jar;L:\git\scala\AkkaRouterTest\target\scala-2.11\test-classes;L:\git\scala\AkkaRouterTest\target\scala-2.11\classes;C:\Users\kot\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.11.2.jar;C:\Users\kot\.ivy2\cache\com.typesafe\config\bundles\config-1.2.1.jar;C:\Users\kot\.ivy2\cache\com.typesafe.akka\akka-actor_2.11\jars\akka-actor_2.11-2.3.5.jar;C:\Users\kot\.ivy2\cache\com.typesafe.akka\akka-testkit_2.11\jars\akka-testkit_2.11-2.3.5.jar;C:\Users\kot\.ivy2\cache\org.scala-lang\scala-reflect\jars\scala-reflect-2.11.2.jar;C:\Users\kot\.ivy2\cache\org.scala-lang.modules\scala-xml_2.11\bundles\scala-xml_2.11-1.0.2.jar;C:\Users\kot\.ivy2\cache\org.scalatest\scalatest_2.11\bundles\scalatest_2.11-2.2.1.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 13.1.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner -s RoundRobinTest -showProgressMessages true -C org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporter
Testing started at 17:44 ...
An exception or error caused a run to abort. This may have been caused by a problematic custom reporter.
java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2347)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:141)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Process finished with exit code -1

```
Is it an Intellij bug or scalatest one?

The dependencies are:

```scala
libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.3.5",
  "com.typesafe.akka" %% "akka-testkit" % "2.3.5",
  "org.scalatest" % "scalatest_2.11" % "2.2.1" % "test")
```

**Comment by bvenners** [comment]
I think this was a IntelliJ setup issue. It is unfortunately sometimes non-obvious how to get everything working in an IDE.
