### ISSUE TITLE
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found

### ISSUE THREAD

**Issue by whoisvolos** [scalatest/scalatest#374]
Hi guys
Trying to run tests in my Spark project (project compiles fine), got this error, here goes result of last test:compile

```
last test:compile
[debug] 
[debug] Initial source changes: 
[debug] 	removed:Set()
[debug] 	added: Set(/home/whoisvolos/repos/hadoop/nextgr/cosine-spark/src/test/scala/ru/ozon/JSONTests.scala)
[debug] 	modified: Set()
[debug] Removed products: Set()
[debug] External API changes: API Changes: Set()
[debug] Modified binary dependencies: Set()
[debug] Initial directly invalidated sources: Set(/home/whoisvolos/repos/hadoop/nextgr/cosine-spark/src/test/scala/ru/ozon/JSONTests.scala)
[debug] 
[debug] Sources indirectly invalidated by:
[debug] 	product: Set()
[debug] 	binary dep: Set()
[debug] 	external source: Set()
[debug] All initially invalidated sources: Set(/home/whoisvolos/repos/hadoop/nextgr/cosine-spark/src/test/scala/ru/ozon/JSONTests.scala)
[debug] Recompiling all 1 sources: invalidated sources (1) exceeded 50.0% of all sources
[info] Compiling 1 Scala source to /home/whoisvolos/repos/hadoop/nextgr/cosine-spark/target/scala-2.10/test-classes...
[debug] Getting compiler-interface from component compiler for Scala 2.10.4
[debug] Getting compiler-interface from component compiler for Scala 2.10.4
[debug] Running cached compiler 12383f, interfacing (CompilerInterface) with Scala compiler version 2.10.4
[debug] Calling Scala compiler with arguments  (CompilerInterface):
[debug] 	-feature
[debug] 	-language:reflectiveCalls
[debug] 	-bootclasspath
[debug] 	/usr/lib/jvm/jdk1.7.0_17/jre/lib/resources.jar:/usr/lib/jvm/jdk1.7.0_17/jre/lib/rt.jar:/usr/lib/jvm/jdk1.7.0_17/jre/lib/sunrsasign.jar:/usr/lib/jvm/jdk1.7.0_17/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.7.0_17/jre/lib/jce.jar:/usr/lib/jvm/jdk1.7.0_17/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.7.0_17/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.7.0_17/jre/classes:/home/whoisvolos/.sbt/boot/scala-2.10.4/lib/scala-library.jar
[debug] 	-classpath
[debug] 	/home/whoisvolos/repos/hadoop/nextgr/cosine-spark/target/scala-2.10/test-classes:/home/whoisvolos/repos/hadoop/nextgr/cosine-spark/target/scala-2.10/cosine-spark_2.10-1.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.spark/spark-core_2.10/jars/spark-core_2.10-1.0.2.jar:/home/whoisvolos/.ivy2/cache/xmlenc/xmlenc/jars/xmlenc-0.52.jar:/home/whoisvolos/.ivy2/cache/commons-configuration/commons-configuration/jars/commons-configuration-1.6.jar:/home/whoisvolos/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar:/home/whoisvolos/.ivy2/cache/commons-digester/commons-digester/jars/commons-digester-1.8.jar:/home/whoisvolos/.ivy2/cache/commons-beanutils/commons-beanutils/jars/commons-beanutils-1.7.0.jar:/home/whoisvolos/.ivy2/cache/commons-beanutils/commons-beanutils-core/jars/commons-beanutils-core-1.8.0.jar:/home/whoisvolos/.ivy2/cache/org.codehaus.jackson/jackson-mapper-asl/jars/jackson-mapper-asl-1.8.8.jar:/home/whoisvolos/.ivy2/cache/org.codehaus.jackson/jackson-core-asl/jars/jackson-core-asl-1.8.8.jar:/home/whoisvolos/.ivy2/cache/org.apache.curator/curator-recipes/bundles/curator-recipes-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.curator/curator-framework/bundles/curator-framework-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.curator/curator-client/bundles/curator-client-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.5.jar:/home/whoisvolos/.ivy2/cache/org.apache.zookeeper/zookeeper/jars/zookeeper-3.4.5.jar:/home/whoisvolos/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.5.jar:/home/whoisvolos/.ivy2/cache/log4j/log4j/bundles/log4j-1.2.17.jar:/home/whoisvolos/.ivy2/cache/jline/jline/jars/jline-0.9.94.jar:/home/whoisvolos/.ivy2/cache/com.google.guava/guava/bundles/guava-14.0.1.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-plus/jars/jetty-plus-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty.orbit/javax.transaction/orbits/javax.transaction-1.1.1.v201105210645.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-webapp/jars/jetty-webapp-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-xml/jars/jetty-xml-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-util/jars/jetty-util-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-servlet/jars/jetty-servlet-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-security/jars/jetty-security-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-server/jars/jetty-server-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty.orbit/javax.servlet/orbits/javax.servlet-3.0.0.v201112011016.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-continuation/jars/jetty-continuation-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-http/jars/jetty-http-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-io/jars/jetty-io-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty/jetty-jndi/jars/jetty-jndi-8.1.14.v20131031.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty.orbit/javax.mail.glassfish/orbits/javax.mail.glassfish-1.4.1.v201005082020.jar:/home/whoisvolos/.ivy2/cache/org.eclipse.jetty.orbit/javax.activation/orbits/javax.activation-1.1.0.v201105071233.jar:/home/whoisvolos/.ivy2/cache/org.apache.commons/commons-lang3/jars/commons-lang3-3.3.2.jar:/home/whoisvolos/.ivy2/cache/com.google.code.findbugs/jsr305/jars/jsr305-1.3.9.jar:/home/whoisvolos/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.5.jar:/home/whoisvolos/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.5.jar:/home/whoisvolos/.ivy2/cache/com.ning/compress-lzf/bundles/compress-lzf-1.0.0.jar:/home/whoisvolos/.ivy2/cache/org.xerial.snappy/snappy-java/bundles/snappy-java-1.0.5.jar:/home/whoisvolos/.ivy2/cache/com.twitter/chill_2.10/jars/chill_2.10-0.3.6.jar:/home/whoisvolos/.ivy2/cache/com.twitter/chill-java/jars/chill-java-0.3.6.jar:/home/whoisvolos/.ivy2/cache/com.esotericsoftware.kryo/kryo/bundles/kryo-2.21.jar:/home/whoisvolos/.ivy2/cache/com.esotericsoftware.reflectasm/reflectasm/jars/reflectasm-1.07-shaded.jar:/home/whoisvolos/.ivy2/cache/com.esotericsoftware.minlog/minlog/jars/minlog-1.2.jar:/home/whoisvolos/.ivy2/cache/org.objenesis/objenesis/jars/objenesis-1.2.jar:/home/whoisvolos/.ivy2/cache/org.spark-project.akka/akka-remote_2.10/bundles/akka-remote_2.10-2.2.3-shaded-protobuf.jar:/home/whoisvolos/.ivy2/cache/org.spark-project.akka/akka-actor_2.10/jars/akka-actor_2.10-2.2.3-shaded-protobuf.jar:/home/whoisvolos/.ivy2/cache/com.typesafe/config/bundles/config-1.0.2.jar:/home/whoisvolos/.ivy2/cache/io.netty/netty/bundles/netty-3.6.6.Final.jar:/home/whoisvolos/.ivy2/cache/org.spark-project.protobuf/protobuf-java/jars/protobuf-java-2.4.1-shaded.jar:/home/whoisvolos/.ivy2/cache/org.uncommons.maths/uncommons-maths/jars/uncommons-maths-1.2.2a.jar:/home/whoisvolos/.ivy2/cache/org.spark-project.akka/akka-slf4j_2.10/bundles/akka-slf4j_2.10-2.2.3-shaded-protobuf.jar:/home/whoisvolos/.ivy2/cache/org.json4s/json4s-jackson_2.10/jars/json4s-jackson_2.10-3.2.6.jar:/home/whoisvolos/.ivy2/cache/com.thoughtworks.paranamer/paranamer/jars/paranamer-2.6.jar:/home/whoisvolos/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.4.jar:/home/whoisvolos/.sbt/boot/scala-2.10.4/lib/scala-compiler.jar:/home/whoisvolos/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/home/whoisvolos/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.0.jar:/home/whoisvolos/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.0.jar:/home/whoisvolos/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.0.jar:/home/whoisvolos/.ivy2/cache/colt/colt/jars/colt-1.2.0.jar:/home/whoisvolos/.ivy2/cache/concurrent/concurrent/jars/concurrent-1.3.4.jar:/home/whoisvolos/.ivy2/cache/org.apache.mesos/mesos/jars/mesos-0.18.1-shaded-protobuf.jar:/home/whoisvolos/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.0.17.Final.jar:/home/whoisvolos/.ivy2/cache/com.clearspring.analytics/stream/jars/stream-2.5.1.jar:/home/whoisvolos/.ivy2/cache/com.codahale.metrics/metrics-core/bundles/metrics-core-3.0.0.jar:/home/whoisvolos/.ivy2/cache/com.codahale.metrics/metrics-jvm/bundles/metrics-jvm-3.0.0.jar:/home/whoisvolos/.ivy2/cache/com.codahale.metrics/metrics-json/bundles/metrics-json-3.0.0.jar:/home/whoisvolos/.ivy2/cache/com.codahale.metrics/metrics-graphite/bundles/metrics-graphite-3.0.0.jar:/home/whoisvolos/.ivy2/cache/org.tachyonproject/tachyon/jars/tachyon-0.4.1-thrift.jar:/home/whoisvolos/.ivy2/cache/org.apache.ant/ant/jars/ant-1.9.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.ant/ant-launcher/jars/ant-launcher-1.9.0.jar:/home/whoisvolos/.ivy2/cache/commons-io/commons-io/jars/commons-io-2.4.jar:/home/whoisvolos/.ivy2/cache/org.spark-project/pyrolite/jars/pyrolite-2.0.1.jar:/home/whoisvolos/.ivy2/cache/net.sf.py4j/py4j/jars/py4j-0.8.1.jar:/home/whoisvolos/.ivy2/cache/net.java.dev.jets3t/jets3t/jars/jets3t-0.7.1.jar:/home/whoisvolos/.ivy2/cache/commons-httpclient/commons-httpclient/jars/commons-httpclient-3.1.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-client/jars/hadoop-client-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-common/jars/hadoop-common-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-annotations/jars/hadoop-annotations-2.4.0.jar:/home/whoisvolos/.ivy2/cache/commons-cli/commons-cli/jars/commons-cli-1.2.jar:/home/whoisvolos/.ivy2/cache/org.apache.commons/commons-math3/jars/commons-math3-3.1.1.jar:/home/whoisvolos/.ivy2/cache/commons-net/commons-net/jars/commons-net-3.1.jar:/home/whoisvolos/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.3.jar:/home/whoisvolos/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.6.jar:/home/whoisvolos/.ivy2/cache/org.apache.avro/avro/jars/avro-1.7.4.jar:/home/whoisvolos/.ivy2/cache/org.apache.commons/commons-compress/jars/commons-compress-1.4.1.jar:/home/whoisvolos/.ivy2/cache/org.tukaani/xz/jars/xz-1.0.jar:/home/whoisvolos/.ivy2/cache/com.google.protobuf/protobuf-java/bundles/protobuf-java-2.5.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-auth/jars/hadoop-auth-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.2.5.jar:/home/whoisvolos/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.2.4.jar:/home/whoisvolos/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.6.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-hdfs/jars/hadoop-hdfs-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.mortbay.jetty/jetty-util/jars/jetty-util-6.1.26.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-app/jars/hadoop-mapreduce-client-app-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-common/jars/hadoop-mapreduce-client-common-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-yarn-common/jars/hadoop-yarn-common-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-yarn-api/jars/hadoop-yarn-api-2.4.0.jar:/home/whoisvolos/.ivy2/cache/javax.xml.bind/jaxb-api/jars/jaxb-api-2.2.2.jar:/home/whoisvolos/.ivy2/cache/javax.xml.stream/stax-api/jars/stax-api-1.0-2.jar:/home/whoisvolos/.ivy2/cache/javax.activation/activation/jars/activation-1.1.jar:/home/whoisvolos/.ivy2/cache/com.sun.jersey/jersey-core/bundles/jersey-core-1.9.jar:/home/whoisvolos/.ivy2/cache/com.google.inject/guice/jars/guice-3.0.jar:/home/whoisvolos/.ivy2/cache/javax.inject/javax.inject/jars/javax.inject-1.jar:/home/whoisvolos/.ivy2/cache/aopalliance/aopalliance/jars/aopalliance-1.0.jar:/home/whoisvolos/.ivy2/cache/org.sonatype.sisu.inject/cglib/jars/cglib-2.2.1-v20090111.jar:/home/whoisvolos/.ivy2/cache/asm/asm/jars/asm-3.2.jar:/home/whoisvolos/.ivy2/cache/com.sun.jersey/jersey-server/bundles/jersey-server-1.9.jar:/home/whoisvolos/.ivy2/cache/com.sun.jersey/jersey-json/bundles/jersey-json-1.9.jar:/home/whoisvolos/.ivy2/cache/org.codehaus.jettison/jettison/bundles/jettison-1.1.jar:/home/whoisvolos/.ivy2/cache/com.sun.xml.bind/jaxb-impl/jars/jaxb-impl-2.2.3-1.jar:/home/whoisvolos/.ivy2/cache/org.codehaus.jackson/jackson-jaxrs/jars/jackson-jaxrs-1.8.8.jar:/home/whoisvolos/.ivy2/cache/org.codehaus.jackson/jackson-xc/jars/jackson-xc-1.8.8.jar:/home/whoisvolos/.ivy2/cache/com.sun.jersey.contribs/jersey-guice/jars/jersey-guice-1.9.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-yarn-client/jars/hadoop-yarn-client-2.4.0.jar:/home/whoisvolos/.ivy2/cache/com.sun.jersey/jersey-client/bundles/jersey-client-1.9.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-core/jars/hadoop-mapreduce-client-core-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-yarn-server-common/jars/hadoop-yarn-server-common-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-shuffle/jars/hadoop-mapreduce-client-shuffle-2.4.0.jar:/home/whoisvolos/.ivy2/cache/org.apache.hadoop/hadoop-mapreduce-client-jobclient/jars/hadoop-mapreduce-client-jobclient-2.4.0.jar:/home/whoisvolos/.ivy2/cache/javax.servlet/servlet-api/jars/servlet-api-2.5.jar:/home/whoisvolos/.ivy2/cache/org.json4s/json4s-native_2.10/jars/json4s-native_2.10-3.2.10.jar:/home/whoisvolos/.ivy2/cache/org.json4s/json4s-core_2.10/jars/json4s-core_2.10-3.2.10.jar:/home/whoisvolos/.ivy2/cache/org.json4s/json4s-ast_2.10/jars/json4s-ast_2.10-3.2.10.jar:/home/whoisvolos/.ivy2/cache/org.scalatest/scalatest_2.10/bundles/scalatest_2.10-2.2.1.jar
[error] error while loading <root>, error in opening zip file
scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.
	at scala.reflect.internal.MissingRequirementError$.signal(MissingRequirementError.scala:16)
	at scala.reflect.internal.MissingRequirementError$.notFound(MissingRequirementError.scala:17)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:48)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:40)
	at scala.reflect.internal.Mirrors$RootsBase.getModuleOrClass(Mirrors.scala:61)
	at scala.reflect.internal.Mirrors$RootsBase.getPackage(Mirrors.scala:172)
	at scala.reflect.internal.Mirrors$RootsBase.getRequiredPackage(Mirrors.scala:175)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage$lzycompute(Definitions.scala:183)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackage(Definitions.scala:183)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass$lzycompute(Definitions.scala:184)
	at scala.reflect.internal.Definitions$DefinitionsClass.RuntimePackageClass(Definitions.scala:184)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr$lzycompute(Definitions.scala:1024)
	at scala.reflect.internal.Definitions$DefinitionsClass.AnnotationDefaultAttr(Definitions.scala:1023)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses$lzycompute(Definitions.scala:1153)
	at scala.reflect.internal.Definitions$DefinitionsClass.syntheticCoreClasses(Definitions.scala:1152)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode$lzycompute(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.symbolsNotPresentInBytecode(Definitions.scala:1196)
	at scala.reflect.internal.Definitions$DefinitionsClass.init(Definitions.scala:1261)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1290)
	at xsbt.CachedCompiler0$$anon$2.<init>(CompilerInterface.scala:113)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:113)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:99)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:102)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:48)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply$mcV$sp(AggressiveCompile.scala:99)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:99)
	at sbt.compiler.AggressiveCompile$$anonfun$3$$anonfun$compileScala$1$1.apply(AggressiveCompile.scala:99)
	at sbt.compiler.AggressiveCompile.sbt$compiler$AggressiveCompile$$timed(AggressiveCompile.scala:166)
	at sbt.compiler.AggressiveCompile$$anonfun$3.compileScala$1(AggressiveCompile.scala:98)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:143)
	at sbt.compiler.AggressiveCompile$$anonfun$3.apply(AggressiveCompile.scala:87)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:39)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:37)
	at sbt.inc.IncrementalCommon.cycle(Incremental.scala:99)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:38)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:37)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:65)
	at sbt.inc.Incremental$.compile(Incremental.scala:37)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:27)
	at sbt.compiler.AggressiveCompile.compile2(AggressiveCompile.scala:157)
	at sbt.compiler.AggressiveCompile.compile1(AggressiveCompile.scala:71)
	at sbt.compiler.AggressiveCompile.apply(AggressiveCompile.scala:46)
	at sbt.Compiler$.apply(Compiler.scala:75)
	at sbt.Compiler$.apply(Compiler.scala:66)
	at sbt.Defaults$.sbt$Defaults$$compileTaskImpl(Defaults.scala:770)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762)
	at sbt.Defaults$$anonfun$compileTask$1.apply(Defaults.scala:762)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
[error] (test:compile) scala.reflect.internal.MissingRequirementError: object scala.runtime in compiler mirror not found.

```

And build.sbt
```sbt
name := "cosine-spark"

version := "1.0"

scalaVersion := "2.10.4"

libraryDependencies += "org.apache.spark" %% "spark-core" % "1.0.2"

libraryDependencies += "org.apache.hadoop" % "hadoop-client" % "2.4.0"

libraryDependencies += "org.json4s" %% "json4s-native" % "3.2.10"

libraryDependencies += "org.scalatest" % "scalatest_2.10" % "2.2.1" % "test"

resolvers += "Akka Repository" at "http://repo.akka.io/releases/"

mainClass := Some("me.sergey.spark.cosine.Driver")

scalacOptions += "-feature"

```
sbt shows no errors in update but test command fails
Test is prettry simple just for compile attempt:
```scala
package me.sergey.simpletests

class TestOne extends FlatSpec {
  "1" should "equals to 1" in {
    assert(1 == 1)
  }
}
```

**Comment by bvenners** [comment]
I tried your build.sbt but there's an unresolved transitive dependency. Perhaps you have a resolver in a different file? Anyway, this is more a setup kind of question that's best asked in scalatest-users. Please follow up there if you still need help with it.
