### ISSUE TITLE
OutOfMemoryError on "sbt test"

### ISSUE THREAD

**Issue by janesser** [scalatest/scalatest#480]
"sbt test" runs into OutOfMemoryError.

Same result without SBT_OPTS or with

	SBT_OPTS="-server -Xms512M -Xmx5120M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:NewRatio=8 -XX:MaxPermSize=512M" 

As mentioned in: https://github.com/scalatest/scalatest/pull/235

Last logging:

	[warn] /home/jan/gits/scalatest/src/test/scala/org/scalatest/fixture/UnitFixtureSpec.scala:27: comparing values of types Unit and Unit using `==' will always yield true
	[warn]           if (un == ())
	[warn]                  ^

After several minutes of CPU inactivity OutOfMemoryError:

	java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
		at java.util.concurrent.FutureTask.get(FutureTask.java:188)
		at sbt.ConcurrentRestrictions$$anon$4.take(ConcurrentRestrictions.scala:188)
		at sbt.Execute.next$1(Execute.scala:83)
	Caused by: java.lang.OutOfMemoryError: Java heap space
		at java.util.Arrays.copyOf(Arrays.java:2219)
		at scala.reflect.internal.Scopes$class.newNestedScope(Scopes.scala:436)
		at scala.reflect.internal.SymbolTable.newNestedScope(SymbolTable.scala:16)
		at scala.tools.nsc.typechecker.Contexts$Context.makeNewScope(Contexts.scala:509)
		at scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5216)

I checked with jconsole. At the moment where the CPU starts to idle, memory alloc raises slowly, while GC has no effect. I would look for something like a polling.

**Comment by janesser** [comment]
Without mentioned SBT_OPTS the Error is like:

	Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
		at scala.reflect.internal.Types$TypeRef$.apply(Types.scala:2338)
		at scala.reflect.internal.Types$class.copyTypeRef(Types.scala:3481)
		at scala.reflect.internal.SymbolTable.copyTypeRef(SymbolTable.scala:16)
		at scala.reflect.internal.tpe.TypeMaps$TypeMap.mapOver(TypeMaps.scala:118)

**Comment by janesser** [comment]
Update: SBT_OPTS fails to overwrite sbt defaults. I managed to extend heap and permgen for real by appending "-J-Xmx 6g -J-XX:Maxpermsize 512m"

Compilation is fine now. 

You could possibly extend the building advice.

This issue may be resolved.
