### ISSUE TITLE
RFE: traversable should contain patternMatch ...

### ISSUE THREAD

**Issue by fommil** [scalatest/scalatest#518]
I have a list that is coming back with some part of the elements set to a random number (beyond my control). I'd like to be able to assert on a pattern match to check that the element exists.

Currently I have to do

```scala
val found = things.exists{case .. => true ; case _ => false} 
assert(found)
```

but I'd like to be able to

```scala
things contains patternMatch {...}
```

**Comment by bvenners** [comment]
I believe you can use inspectors or inspector shorthands for what you want. Something like:

scala> import org.scalatest._
import org.scalatest._

scala> import Matchers._
import Matchers._

scala> val things = List(Some(1), None, Some(10), None, Some(100))
things: List[Option[Int]] = List(Some(1), None, Some(10), None, Some(100))

scala> atLeast(3, things) should matchPattern { case Some(num: Int) if num >= 10 => }
org.scalatest.exceptions.TestFailedException: 'atLeast(3)' inspection failed, because only 2 elements satisfied the assertion block:
  at index 0, Some(1) did not match the given pattern (<console>:15),
  at index 1, None did not match the given pattern (<console>:15),
  at index 3, None did not match the given pattern (<console>:15)
in List(Some(1), None, Some(10), None, Some(100))
  at org.scalatest.InspectorsHelper$.doForAtLeast(Inspectors.scala:663)
  at org.scalatest.Matchers$class.doCollected(Matchers.scala:3147)
  at org.scalatest.Matchers$.doCollected(Matchers.scala:7224)
  at org.scalatest.Matchers$ResultOfCollectedAny.should(Matchers.scala:4875)
  ... 43 elided

If this addresses your need, please go ahead and close this issue.

Thanks.

Bill

**Comment by fommil** [comment]
oh cool! I hadn't thought about it that way
