### ISSUE TITLE
FreeSpec : uncaught exception

### ISSUE THREAD

**Issue by etaty** [scalatest/scalatest#539]
```sbt
scalaVersion := "2.11.6"

libraryDependencies ++= Seq(
  "org.scalatest" % "scalatest_2.11" % "2.2.4" % "test"
)
```
```scala
import org.scalatest.FreeSpec

class TestFreeSpec extends FreeSpec {
  "some" - {
    "test" - {
      fail()
    }
  }
}
```

```
  % sbt
[info] Loading project definition from /Users/valerian/projects/scalatest-uncaught/project
[info] Set current project to scalatest-uncaught (in build file:/Users/valerian/projects/scalatest-uncaught/)
> test
[trace] Stack trace suppressed: run last test:test for the full output.
[error] Could not run test TestFreeSpec: org.scalatest.exceptions.TestFailedException
[info] Run completed in 116 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error during tests:
[error] 	TestFreeSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 1 s, completed Mar 30, 2015 11:39:55 PM
> last test:test
[debug] Running TaskDef(TestFreeSpec, org.scalatest.tools.Framework$$anon$1@50d92f57, false, [SuiteSelector])
org.scalatest.exceptions.TestFailedException
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:493)
	at org.scalatest.FreeSpec.newAssertionFailedException(FreeSpec.scala:1740)
	at org.scalatest.Assertions$class.fail(Assertions.scala:1313)
	at org.scalatest.FreeSpec.fail(FreeSpec.scala:1740)
	at TestFreeSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TestFreeSpec.scala:6)
	at TestFreeSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(TestFreeSpec.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at org.scalatest.SuperEngine.registerNestedBranch(Engine.scala:613)
	at org.scalatest.FreeSpecLike$FreeSpecStringWrapper.$minus(FreeSpecLike.scala:241)
	at TestFreeSpec$$anonfun$1.apply$mcV$sp(TestFreeSpec.scala:5)
	at org.scalatest.SuperEngine.registerNestedBranch(Engine.scala:613)
	at org.scalatest.FreeSpecLike$FreeSpecStringWrapper.$minus(FreeSpecLike.scala:241)
	at TestFreeSpec.<init>(TestFreeSpec.scala:4)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at java.lang.Class.newInstance(Class.java:438)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:646)
	at sbt.TestRunner.runTest$1(TestFramework.scala:84)
	at sbt.TestRunner.run(TestFramework.scala:94)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:219)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:207)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:219)
	at sbt.TestFunction.apply(TestFramework.scala:224)
	at sbt.Tests$$anonfun$7.apply(Tests.scala:196)
	at sbt.Tests$$anonfun$7.apply(Tests.scala:196)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:45)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] Could not run test TestFreeSpec: org.scalatest.exceptions.TestFailedException
[info] Run completed in 116 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 0
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] No tests were executed.
[error] Error during tests:
[error] 	TestFreeSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
>
```

https://github.com/etaty/scalatest-uncaught

**Comment by bvenners** [comment]
The problem here is that "-" introduces a scope, not a test. Instead, "in" introduces a test. What we should do though is generate a better error message when someone does this, because it is an easy thing to do. This should work fine:

import org.scalatest.FreeSpec

class TestFreeSpec extends FreeSpec {
  "some" - {
    "test" in {
      fail()
    }
  }
}

**Comment by etaty** [comment]
ah thanks
