### ISSUE TITLE
Serialization issues when testing Apache Spark 1.2 (GraphX)

### ISSUE THREAD

**Issue by imarios** [scalatest/scalatest#542]
I try to create a simple Graph in GraphX and test it using ScalaTest. When I do that I get the following serialization error: 

```
Job aborted due to stage failure: Task not serializable: java.io.NotSerializableException: org.scalatest.Assertions$AssertionsHelper
org.apache.spark.SparkException: Job aborted due to stage failure: Task not serializable: java.io.NotSerializableException: org.scalatest.Assertions$AssertionsHelper
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1214)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1203)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1202)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1202)
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$submitMissingTasks(DAGScheduler.scala:879)
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$submitStage(DAGScheduler.scala:778)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$org$apache$spark$scheduler$DAGScheduler$$submitStage$4.apply(DAGScheduler.scala:781)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$org$apache$spark$scheduler$DAGScheduler$$submitStage$4.apply(DAGScheduler.scala:780)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$submitStage(DAGScheduler.scala:780)
	at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:762)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor$$anonfun$receive$2.applyOrElse(DAGScheduler.scala:1389)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessActor.aroundReceive(DAGScheduler.scala:1375)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Here is my Spark Template 

```scala
class SparkTestTemplate  extends FunSuite with BeforeAndAfter with Matchers {
 before {
    CTools.setProperty(Constants.PROP_UBER_GRAPH_URI, userGraphFileLocation)
    CTools.getProperty(Constants.PROP_UBER_GRAPH_URI) should not be null
    CTools.setProperty(Constants.PROP_GRAPHDB_PERSISTENCE_TYPE, "inmemory")
    CTools.getProperty(Constants.PROP_GRAPHDB_PERSISTENCE_TYPE) should not be null

    System.clearProperty("spark.master.port")
    System.clearProperty("spark.driver.port")
    System.clearProperty("spark.hostPort")
    System.setProperty("spark.cleaner.ttl", "300")
    sc = new SparkContext(conf)
  }

  after {
    System.clearProperty("spark.master.port")
    System.clearProperty("spark.driver.port")
    System.clearProperty("spark.hostPort")
    sc.stop()
    sc = null
  }
}
```

Here is my test class

```scala
class GraphTest extends SparkTestTemplate {
    test("simple test") {
       case class N1(n: String) extends Serializable 
       val vertexRDD: RDD[(Long,N1)] = sc.parallelize( Seq( (1L, N1("a") ), (2L, N1("b")), (3L, N1("b"))) )
       val edgeRDD: RDD[ Edge[String]] = sc.parallelize( Seq( Edge(1L, 2L, "hi"), Edge(2L, 3L, "gg") ) )

       val graph = Graph(vertexRDD, edgeRDD)
       println(graph.numVertices)
    }
}
```

**Comment by rfries** [comment]
I suspect the issue here is that since N1 is an inner class, serializing it is pulling in the test class itself into the object graph, which I suspect is not what you want.  Could you try declaring N1 at top-level scope? e.g.

```scala
case class N1(n: String) extends Serializable

class GraphTest extends SparkTestTemplate {
    test("simple test") {
       val vertexRDD: RDD[(Long,N1)] = sc.parallelize( Seq( (1L, N1("a") ), (2L, N1("b")), (3L, N1("b"))) )
       val edgeRDD: RDD[ Edge[String]] = sc.parallelize( Seq( Edge(1L, 2L, "hi"), Edge(2L, 3L, "gg") ) )

       val graph = Graph(vertexRDD, edgeRDD)
       println(graph.numVertices)
    }
}
```

**Comment by rfries** [comment]
Closing for now; if you continue having problems after trying the suggestion above, let us know and we can revisit the issue.

**Comment by MatthewEdge** [comment]
I just wanted to comment that this solution worked for us. We were fighting with a similar issue and moving the case class outside of the ScalaTest class' scope solved the TaskNotSerializable error.

Thank you!
