### ISSUE TITLE
DiagrammedAssertions can't handle Java static fields

### ISSUE THREAD

**Issue by pniederw** [scalatest/scalatest#615]
`assert(BigInteger.ZERO == BigInteger.ZERO)` fails even on versions that have fix #583 (tested with 3.0.0-SNAP5).

```
Error:(18, 11) exception during macro expansion: 
scala.reflect.macros.TypecheckException: inferred type arguments [java.math.BigInteger.type] do not conform to method simpleExpr's type parameter bounds [T]
	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:34)
	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2$$anonfun$apply$1.apply(Typers.scala:28)
	at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
	at scala.reflect.macros.contexts.Typers$$anonfun$3.apply(Typers.scala:24)
	at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
	at scala.reflect.macros.contexts.Typers$$anonfun$withContext$1$1.apply(Typers.scala:25)
	at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
	at scala.reflect.macros.contexts.Typers$$anonfun$1.apply(Typers.scala:23)
	at scala.reflect.macros.contexts.Typers$class.withContext$1(Typers.scala:25)
	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
	at scala.reflect.macros.contexts.Typers$$anonfun$typecheck$2.apply(Typers.scala:28)
	at scala.reflect.internal.Trees$class.wrappingIntoTerm(Trees.scala:1716)
	at scala.reflect.internal.SymbolTable.wrappingIntoTerm(SymbolTable.scala:16)
	at scala.reflect.macros.contexts.Typers$class.withWrapping$1(Typers.scala:26)
	at scala.reflect.macros.contexts.Typers$class.typecheck(Typers.scala:28)
	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
	at scala.reflect.macros.contexts.Context.typecheck(Context.scala:6)
	at scala.reflect.macros.Typers$class.typeCheck(Typers.scala:58)
	at scala.reflect.macros.contexts.Context.typeCheck(Context.scala:6)
	at org.scalactic.MacroOwnerRepair.repairOwners(MacroOwnerRepair.scala:34)
	at org.scalatest.DiagrammedExprMacro.genMacro(DiagrammedExprMacro.scala:414)
	at org.scalatest.DiagrammedAssertionsMacro$.macroImpl(DiagrammedAssertionsMacro.scala:79)
	at org.scalatest.DiagrammedAssertionsMacro$.assert(DiagrammedAssertionsMacro.scala:85)
    assert(BigInteger.ZERO == BigInteger.ZERO)
          ^
```

**Comment by cheeseng** [comment]
@pniederw thanks for reporting this, I have worked out a fix: 

https://github.com/cheeseng/scalatest/commit/abfdd79a258695a81e34442e97526ef1cf13acb7

Hopefully it will get into the next 3.0.0 release soon.

Thanks.
