### ISSUE TITLE
Running test in intellij crossproject scala.js 0.6.5 scalatest 3.0.0-M9 fails

### ISSUE THREAD

**Issue by katrinsharp** [scalatest/scalatest#743]
The stack trace that I'm getting:

/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/java -Didea.launcher.port=7535 "-Didea.launcher.bin.path=/Applications/IntelliJ IDEA 14 CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Users/katrin/Library/Application Support/IdeaIC14/Scala/lib/scala-plugin-runners.jar:/Users/katrin/Library/Application Support/IdeaIC14/Scala/lib/Runners.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/katrin/.ivy2/cache/org.scala-js/scalajs-library_2.11/jars/scalajs-library_2.11-0.6.5.jar:/Users/katrin/.ivy2/cache/org.scala-js/scalajs-test-interface_2.11/jars/scalajs-test-interface_2.11-0.6.5.jar:/Users/katrin/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar:/Users/katrin/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.7.jar:/Users/katrin/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/Users/katrin/.ivy2/cache/org.scalacheck/scalacheck_sjs0.6_2.11/jars/scalacheck_sjs0.6_2.11-1.12.5.jar:/Users/katrin/.ivy2/cache/org.scalactic/scalactic_sjs0.6_2.11/bundles/scalactic_sjs0.6_2.11-3.0.0-M9.jar:/Users/katrin/.ivy2/cache/org.scalatest/scalatest_sjs0.6_2.11/bundles/scalatest_sjs0.6_2.11-3.0.0-M9.jar:/Users/katrin/.ivy2/cache/org.scoverage/scalac-scoverage-plugin_2.11/jars/scalac-scoverage-plugin_2.11-1.1.0.jar:/Users/katrin/.ivy2/cache/org.scoverage/scalac-scoverage-runtime_2.11/jars/scalac-scoverage-runtime_2.11-1.1.0.jar:/Users/katrin/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/Users/katrin/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar:/Users/katrin/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/Users/katrin/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.12.5.jar:/Users/katrin/.ivy2/cache/org.scalactic/scalactic_2.11/bundles/scalactic_2.11-3.0.0-M9.jar:/Users/katrin/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-3.0.0-M9.jar:/Applications/IntelliJ IDEA 14 CE.app/Contents/lib/idea_rt.jar" com.intellij.rt.execution.application.AppMain org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner -s com.imprivata.cortext.cscore.FailureSupportTest -showProgressMessages true -C org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporter
Testing started at 10:47 AM ...
java.lang.IllegalArgumentException: Argument not supported by ScalaTest-js: -C
	at org.scalatest.tools.ArgsParser$.parseArgs(ArgsParser.scala:191)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:883)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 0

**Comment by jg123** [comment]
I am getting the same error in IJ 14.
```
java.lang.IllegalArgumentException: Argument not supported by ScalaTest-js: -C
	at org.scalatest.tools.ArgsParser$.parseArgs(ArgsParser.scala:191)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:883)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 0
```

**Comment by bvenners** [comment]
Here is the offending code:

https://github.com/scalatest/scalatest/blob/3.0.x/scalatest/src/main/scala/org/scalatest/tools/ArgsParser.scala#L291

The problem here is that -C has no meaning in ScalaTest.js, because that is for concurrent execution. So we throw IAE. But we didn't think about cross builds. So probably what we should do is either silently ignore it on Scala.js, or perhaps emit a warning. That warning would be annoying in cross builds though.

Moreover, if you look through that file you'll find other command line parameters that throw IAE if they appear under Scala.js. Perhaps some of those should be allowed for cross builds. Unfortunately we don't have comments as to what each command line param is. For that you'd need to look at the Runner Scaladoc:

http://doc.scalatest.org/2.2.4/index.html#org.scalatest.tools.Runner$

I'll look through and see if there are others, but if you can look through also that would help. Also, would you prefer a warning or silence when -C is encountered under Scala.js?

Bill

**Comment by jg123** [comment]
Silence would be golden.

This is a cross build.

Since this is intellij calling Runner, I am not sure what parameters they are passing. I'll try to figure it out. Do you talk to those guys? Their scala plugin has a method called `runScalaTest2`:
`org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)`
I wonder if they are working on a `runScalaTest3` method as well...

**Comment by bvenners** [comment]
We do talk to them indeed. Main problem this year is that the Scala.js support has been so overwhelming that smaller (though important) issues get pushed to the back burner. One other way to deal with this could in theory be that IDEs don't pass to ScalaTest.js parameters that don't make sense under Scala.js, like -C, but really I think cross building is a ScalaTest use case, so we should deal internally. I was leaning towards silence, but didn't want to lead the witness. We can just document that -C on Scala.js has no effect. That'll be fine.

**Comment by katrinsharp** [comment]
I would also agree that silence is good option.

Thanks,
Katrin

On Thursday, November 5, 2015, Bill Venners <notifications@github.com>
wrote:

> We do talk to them indeed. Main problem this year is that the Scala.js
> support has been so overwhelming that smaller (though important) issues get
> pushed to the back burner. One other way to deal with this could in theory
> be that IDEs don't pass to ScalaTest.js parameters that don't make sense
> under Scala.js, like -C, but really I think cross building is a ScalaTest
> use case, so we should deal internally. I was leaning towards silence, but
> didn't want to lead the witness. We can just document that -C on Scala.js
> has no effect. That'll be fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/743#issuecomment-154133899>
> .
>


-- 
Best Regards,
Katrin

**Comment by jg123** [comment]
Here is the code that is calling scalatest: `https://github.com/JetBrains/intellij-scala/blob/5f9d710d539c104d4915c04cbaa2ea997a44fd48/Runners/src/org/jetbrains/plugins/scala/testingSupport/scalaTest/ScalaTestRunner.java#L49`

Looks like arguments that can be called are s, testName, showProgressMessages, failedTests, setScalaTestVersion, and C.

C seems to be the only argument here that could throw the exception.

**Comment by bvenners** [comment]
Great, thanks for tracking that down. I expect to deploy a SNAP shortly for you to try. Will post here once that's out.

**Comment by jg123** [comment]
Thank you!

**Comment by bvenners** [comment]
Actually -C is for custom reporters, not parallel execution, so eventually that will actually work. We'll silently ignore it for now, and document that, but later we'll just use the custom reporter. Can you confirm you have a custom reporter being used in your build? Or is that perhaps a custom reporter added by IntelliJ itself? If the latter, then ignoring it may mean things won't work on IntelliJ. Regardless I'll deploy a SNAP and with the silent ignore and you can try it and let me know.

**Comment by jg123** [comment]
No custom reporter in our build. It is coming from intellij itself. Let me see if I can find what reporter they are calling.

**Comment by jg123** [comment]
Custom reporter is `org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporter`:

https://github.com/JetBrains/intellij-scala/blob/36b1d0abf7bdfd61d70ec18de6ccc236fb2fa395/src/org/jetbrains/plugins/scala/testingSupport/test/scalatest/ScalaTestRunConfiguration.scala#L30

which can be found here:

https://github.com/JetBrains/intellij-scala/blob/5f9d710d539c104d4915c04cbaa2ea997a44fd48/Runners/src/org/jetbrains/plugins/scala/testingSupport/scalaTest/ScalaTestReporter.java

**Comment by bvenners** [comment]
OK, this is their reporter for getting at the test results and displaying them in the GUI. Can you elaborate on how you are doing a cross build? Do you have an sbt build that you import into IntelliJ, and that sbt build is doing a cross build? Are you actually building artifacts for Scala.js using IntelliJ somehow? Are you attempting to run the tests on Scala.js through IntelliJ? I have not even thought about how IDEs would integrate with Scala.js. What are they doing in that area?

**Comment by jg123** [comment]
We have an sbt build that I have imported into intellij. I can compile and create jars from sbt tasks, but I was simply using the Intellij IDE to right-click on a test specific to the JS code and select Execute test. I was assuming I would get a js file and scalatest.js would execute tests in its sandbox, selenium, maybe? I am grasping at straws now.

**Comment by bvenners** [comment]
I'm not sure what's supposed to happen either. We should bring the IntelliJ folks in on the conversation. I'll email them and point them to this discussion.

I have released 3.0.0-SNAP11, which should not throw an IllegalArgumentException for -C under Scala.js. Please try that in your project when you get a chance and let me know what happens!

Thanks.

Bill

**Comment by jg123** [comment]
Sounds good. Doesn't complain about -C, but it doesn't like the classname after it:
```
java.lang.IllegalArgumentException: Argument unrecognized by ScalaTest's Runner: org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestReporterWithLocation
	at org.scalatest.tools.ArgsParser$.parseArgs(ArgsParser.scala:266)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:883)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
Probably ignore that too for now.

**Comment by bvenners** [comment]
Sorry, that's a bug on my part. Will fix and do another SNAP.

**Comment by cheeseng** [comment]
@katrinsharp @jg123 @bvenners  Sorry just notice this reported issue, unfortunately I think Runner won't work with running scala-js, indeed Runner is not   included in the scalatest sjs jar.  In SBT scala-js provides an adapter that does the plumbing of running the tests in js env, and I think the same plumbing is needed when intellij runs them.

**Comment by bvenners** [comment]
I sent an email to the IntelliJ folks. First step should probably be to find out how they want to handle Scala.jvm/Scala.js cross builds.

**Comment by hkirk** [comment]
I've just seen this error in the newest IJ 2016.3 (sure it did not happen in latest EAP but haven't tested yet.) with scalatest 3.0.0 and 3.0.1.

`java.lang.IllegalArgumentException: Argument not supported by ScalaTest-js: -C
	at org.scalatest.tools.ArgsParser$.parseArgs(ArgsParser.scala:191)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:883)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

**Comment by hkirk** [comment]
I had both scalatest as ScalaJS and JVM dependecy like this
`"org.scalatest" %%% "scalatest" % "3.0.0" % "test",
  "org.scalatest" %% "scalatest" % "3.0.0" % "test"`

Seems that removing the first solves my problem.

Can't remember exactly why, but can remember that adding both dependencies was a solution I found on at Github Issue eiter  in ScalaTest or ScalaJs

**Comment by ryan-williams** [comment]
(Seeing this `-C` issue with sjs 0.6.21, scalatest 3.0.4, scala plugin 2017.3.603)

**Comment by evbo** [comment]
Just upgraded to IntelliJ  2019.2 and am seeing this issue:

```bash
java.lang.NoClassDefFoundError: org/scalatest/tools/Runner
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:133)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:27)
Caused by: java.lang.ClassNotFoundException: org.scalatest.tools.Runner
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
```

My cross project has dependencies set like:

```scala
lazy val core = crossProject(JSPlatform, JVMPlatform).crossType(CrossType.Pure).in(file("shared"))
  .jvmSettings(
    libraryDependencies ++= Seq(
      "io.circe" %% "circe-core" % Dependencies.circeVersion,
      "io.circe" %% "circe-generic" % Dependencies.circeVersion,
      "io.circe" %% "circe-parser" % Dependencies.circeVersion,
      "org.scalatest" %% "scalatest" % Dependencies.scalaTestVersion % Test
    )
  )
  .jsSettings(
    libraryDependencies ++= Seq(
      "io.circe" %%% "circe-core" % Dependencies.circeVersion,
      "io.circe" %%% "circe-generic" % Dependencies.circeVersion,
      "io.circe" %%% "circe-parser" % Dependencies.circeVersion,
      "org.scalatest" %%% "scalatest" % Dependencies.scalaTestVersion % Test
    )
  )
```
