### ISSUE TITLE
Play 2.4 with Scalatest-plus getting: "java.net.SocketException: Connection reset" 

### ISSUE THREAD

**Issue by yonigoldberg** [scalatest/scalatest#772]
Running play 2.4.3 with:
  "org.scalatest" %% "scalatest" % "2.2.5" % "test",
  "org.scalatestplus" %% "play" % "1.4.0-M3" % "test,it"

When we run the tests locally we never get the error below, only when build on travis. 
Any suggestion on how to troubleshoot?

Exception in thread "Thread-9" Exception in thread "Thread-5" java.net.SocketException: Connection reset
    at java.net.SocketInputStream.read(SocketInputStream.java:189)
    at java.net.SocketInputStream.read(SocketInputStream.java:121)
    at java.net.SocketInputStream.read(SocketInputStream.java:203)
    at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2296)
    at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:2589)
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2599)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at sbt.React.react(ForkTests.scala:114)
    at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
    at java.lang.Thread.run(Thread.java:745)
java.io.EOFException
    at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2601)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1319)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:953)
    at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:942)
    at java.lang.Thread.run(Thread.java:745)

**Comment by maxsidorov** [comment]
Hi @yonigoldberg, how did you solve this issue?

**Comment by zsaltys** [comment]
@yonigoldberg got a similar issue.. how did you solve it?

**Comment by BillOTei** [comment]
up on this one having the same issue on CircleCI build @yonigoldberg @zsaltys
