### ISSUE TITLE
IllegalArgumentException thrown when executing tests in sbt

### ISSUE THREAD

**Issue by jvican** [scalatest/scalatest#873]
I'm trying to use the latest version of scalatest to get scalajs support for scala/pickling.
  
I'm getting a pretty weird error. Before I was using `2.11` and everything was working. Now, I get this exception:
```
java.lang.IllegalArgumentException
	at scala.tools.asm.ByteVector.putUTF8(ByteVector.java:213)
	at scala.tools.asm.ClassWriter.newUTF8(ClassWriter.java:1092)
	at scala.tools.asm.ClassWriter.newString(ClassWriter.java:1525)
	at scala.tools.asm.ClassWriter.newConstItem(ClassWriter.java:1042)
	at scala.tools.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1134)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genConstant(GenASM.scala:1578)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.scala$tools$nsc$backend$jvm$GenASM$JPlainBuilder$$genInstr$1(GenASM.scala:2292)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder$$anonfun$genBlock$1$2.apply(GenASM.scala:2223)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder$$anonfun$genBlock$1$2.apply(GenASM.scala:2209)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
	at scala.tools.nsc.backend.icode.BasicBlocks$BasicBlock.foreach(BasicBlocks.scala:195)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genBlock$1(GenASM.scala:2209)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genBlocks$1(GenASM.scala:2147)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genCode(GenASM.scala:2742)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genMethod(GenASM.scala:1467)
	at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1337)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:198)
	at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:204)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:829)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:820)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:818)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
  
Apparently, this error has already been reported in the scala issue tracker. It is caused by the JVM not supporting strings of more than 65k (there are only two bytes for storing the length of a string). See the comments in the [original scala issue](https://issues.scala-lang.org/browse/SI-7527) and [this thread](https://groups.google.com/forum/#!topic/gatling/WMiL81bVWoI). Also, ScalaJS complains of `Encoded string too long` so this is definitely the root of the issue.
  
Scala version: `2.11.7`.
Scalatest version: `3.0.0-M15`.
  
To reproduce, fork scala-pickling (make sure you're in the 0.11.x branch) and then change the scalatest version in `project/Dependencies.scala`.
  
My guess is that scalatest is doing something weird with strings and somehow generates a string bigger thank 65k. It is pretty difficult to isolate the test case that is causing this problem (we have around 300 tests in scala/pickling).

**Comment by bvenners** [comment]
Hi Jorge,

One thing that springs to mind is encoded strings used in Spec (RefSpec in
the latest 3.0), but that doesn't exist on Scala.js.

Can you reveal a bit more about your test suite? What style traits and
mixin traits do you use?

Bill

On Thu, May 5, 2016 at 2:03 PM, Jorge <notifications@github.com> wrote:

> I'm trying to use the latest version of scalatest to get scalajs support
> for scala/pickling.
>
> I'm getting a pretty weird error. Before I was using 2.11 and everything
> was working. Now, I get this exception:
>
> java.lang.IllegalArgumentException
>     at scala.tools.asm.ByteVector.putUTF8(ByteVector.java:213)
>     at scala.tools.asm.ClassWriter.newUTF8(ClassWriter.java:1092)
>     at scala.tools.asm.ClassWriter.newString(ClassWriter.java:1525)
>     at scala.tools.asm.ClassWriter.newConstItem(ClassWriter.java:1042)
>     at scala.tools.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1134)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genConstant(GenASM.scala:1578)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.scala$tools$nsc$backend$jvm$GenASM$JPlainBuilder$$genInstr$1(GenASM.scala:2292)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder$$anonfun$genBlock$1$2.apply(GenASM.scala:2223)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder$$anonfun$genBlock$1$2.apply(GenASM.scala:2209)
>     at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
>     at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
>     at scala.tools.nsc.backend.icode.BasicBlocks$BasicBlock.foreach(BasicBlocks.scala:195)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genBlock$1(GenASM.scala:2209)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genBlocks$1(GenASM.scala:2147)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genCode(GenASM.scala:2742)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genMethod(GenASM.scala:1467)
>     at scala.tools.nsc.backend.jvm.GenASM$JPlainBuilder.genClass(GenASM.scala:1337)
>     at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.emitFor$1(GenASM.scala:198)
>     at scala.tools.nsc.backend.jvm.GenASM$AsmPhase.run(GenASM.scala:204)
>     at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
>     at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
>     at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
>     at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
>     at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
>     at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
>     at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:498)
>     at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
>     at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
>     at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
>     at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
>     at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
>     at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
>     at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
>     at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
>     at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
>     at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
>     at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
>     at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
>     at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
>     at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
>     at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
>     at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
>     at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
>     at sbt.inc.Incremental$.compile(Incremental.scala:61)
>     at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
>     at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
>     at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
>     at sbt.Compiler$.compile(Compiler.scala:128)
>     at sbt.Compiler$.compile(Compiler.scala:114)
>     at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:829)
>     at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:820)
>     at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:818)
>     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>     at sbt.std.Transform$$anon$4.work(System.scala:63)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>     at sbt.Execute.work(Execute.scala:235)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
>     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>     at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
>
> Apparently, this error has already been reported in the scala issue
> tracker. It is caused by the JVM not supporting strings of more than 65k
> (there are only two bytes for storing the length of a string). See the
> comments in the original scala issue
> <https://issues.scala-lang.org/browse/SI-7527> and this thread
> <https://groups.google.com/forum/#!topic/gatling/WMiL81bVWoI>. Also,
> ScalaJS complains of Encoded string too long so this is definitely the
> root of the issue.
>
> Scala version: 2.11.7.
> Scalatest version: 3.0.0-M15.
>
> To reproduce, fork scala-pickling (make sure you're in the 0.11.x branch)
> and then change the scalatest version in project/Dependencies.scala.
>
> My guess is that scalatest is doing something weird with strings and
> somehow generates a string bigger thank 65k. It is pretty difficult to
> isolate the test case that is causing this problem (we have around 300
> tests in scala/pickling).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/873>
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by jvican** [comment]
Hi Bill, thanks for your feedback.
  
At this moment, I'm getting this error on the JVM without any Scalajs integration so far (my colleague has done this and got that error).
  
Sure, we're using plain asserts and the `FunSuite`. There are some minor cases in which we use scalacheck + scalatest, but still mixing in FunSuite. An example here: https://github.com/scala/pickling/blob/03bb0836600ad5c6892b7849f006f22f1f908417/core/src/test/scala/pickling/run/bytebuffers.scala.
  
Let me know if I can be more concise.

**Comment by bvenners** [comment]
Hi Jorge,

I don't see anything amiss in the ScalaTest code. I wonder if it could be
either the pickling library doing something with a macro, or Scala.js
generating code, or some combination of both. What would be good is if you
could narrow it down to exactly one class.

Bill

On Fri, May 6, 2016 at 2:36 AM, Jorge <notifications@github.com> wrote:

> Hi Bill, thanks for your feedback.
>
> At this moment, I'm getting this error on the JVM without any Scalajs
> integration so far (my colleague has done this and got that error).
>
> Sure, we're using plain asserts and the FunSuite. There are some minor
> cases in which we use scalacheck + scalatest, but still mixing in FunSuite.
> An example here:
> https://github.com/scala/pickling/blob/03bb0836600ad5c6892b7849f006f22f1f908417/core/src/test/scala/pickling/run/bytebuffers.scala
> .
>
> Let me know if I can be more concise.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/873#issuecomment-217397698>
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by jvican** [comment]
Hi Bill,
  
I'll try to narrow it down but it's very unlikely that this is caused by scala pickling, since this error has appeared when changing versions in scalatest, and the scala pickling macros are pretty stable (yet I'm not ruling out this possibility). However, I'll look into this today and try to give you feedback asap.
  
I've been able to get some errors from the safe compiler plugin, but still haven't checked what those errors are reporting. However, notice that Scalajs has nothing to do with the errors I'm reporting, since I'm not using it. This weird behaviour appears with sbt compiling for the JVM.

**Comment by bvenners** [comment]
Hi Jorge,

Hmm. We did see that before on ScalaTest, but it was method names in Spec
trait (called RefSpec in 3.0), and it was actually cause by a bug in the
compiler, which was fixed. If you're not using Spec, then something else
must be generating a long string. I suppose another possibility is our
assert macros. Are you using assertions? I can't imagine one of those
generating such a big string, but there is the possibility of a bug. It
would be good to narrow it down to one source file if you can.

When Scala.js says Encoded string too long does it give you the beginning
or end of the string?

By the way, I think you are using 3.0.0-M15 now. What version were you
using before when you didn't see the problem?

Bill

On Fri, May 6, 2016 at 6:24 AM, Jorge <notifications@github.com> wrote:

> Hi Bill,
>
> I'll try to narrow it down but it's very unlikely that this is caused by
> scala pickling, since this error has appeared when changing versions in
> scalatest, and the scala pickling macros are pretty stable (yet I'm not
> ruling out this possibility). However, I'll look into this today and try to
> give you feedback asap.
>
> I've been able to get some errors from the safe compiler plugin, but still
> haven't checked what those errors are reporting. However, notice that
> Scalajs has nothing to do with the errors I'm reporting, since I'm not
> using it. This weird behaviour appears with sbt compiling for the JVM.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/scalatest/scalatest/issues/873#issuecomment-217438691>
>



-- 
Bill Venners
Artima, Inc.
http://www.artima.com

**Comment by jvican** [comment]
Hi Bill,
  
I already found out what's going on. It turns out that the error comes from the interaction between the picklers and the assert macros. In one fix, we were doing something like `assert(a.pickle[T].unpickle[T] === ???)`. The pickle and unpickle were expanded and the resulting generated code exceeded the 65k length limit imposed by the code generators. Your assert macro is getting this condition (the tree that you want to test) and converting it into a `String`, therefore producing the weird compiler error already explained above.
  
I've fixed this in our test suite, you could also push a fix that will inspect the condition tree and figure out if it exceeds the aforementioned limit (this could turn out not to be possible). But, it may not be worth it... future users very rarely will get this error.
  
Anyway, I'd propose to mark this issue as `documentation` and close it.
  
My fix: https://github.com/jvican/pickling/commit/0329c68e042496d416010abb9dd0037f573ea061.

**Comment by cheeseng** [comment]
@jvican not sure if I remember this correctly, if you added the following to your build: 

jsDependencies += RuntimeDOM % "test" 

I wonder would it workaround the problem, I remember I had similar 65K problem and somebody suggested the above to workaround.

**Comment by jvican** [comment]
Hi @cheeseng, good to know if the error appears again in ScalaJS. So far, the main problem was the JVM and there's no other way to address it than the one I proposed (since the length limit is imposed by the same JVM).
  
But still, I'll keep it in mind! Thanks :+1:

**Comment by geekbytes0xff** [comment]
I have the same issue 
but am able to test with sbt console not able to debug test with Intelij
