### ISSUE TITLE
AsyncFreeSpec leads to deadlock in NodeJS environment

### ISSUE THREAD

**Issue by nartamonov** [scalatest/scalatest#874]
Let's write simple spec:

```scala
import org.scalatest.{Matchers, AsyncFreeSpec}

import scala.concurrent.Future

class ProblematicSpec extends AsyncFreeSpec with Matchers {
  "A" - {
    "A1" in {
      Future { 1 shouldEqual 1 }
    }
  }

  "B" - {
    "B1" in {
      Future { 1 shouldEqual 1 }
    }
  }
}
```

If we try to execute this spec compiled with ScalaJS in NodeJS environment then execution will freeze forever. After manual killing nodejs processes we've got:

```
[error] java.util.ConcurrentModificationException: Two threads have apparently attempted to run a suite at the same time. This has resulted in both threads attempting to concurrently change the current Informer. Suite class name: ProblematicSpec
[error]   at $c_ju_ConcurrentModificationException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:23339:14)
[trace] Stack trace suppressed: run last test:test for the full output.
[error]   at $c_ju_ConcurrentModificationException.$c_jl_Throwable.init___T__jl_Throwable(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:23361:8)
[error]   at java.util.ConcurrentModificationException.<init>(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:36234:52)
[error] Could not run test ProblematicSpec: java.net.SocketException: Connection reset
[error]   at org.scalatest.AsyncSuperEngine$$anonfun$runTestImpl$2.apply(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:33803:55)
[error]   at org.scalatest.AsyncSuperEngine$$anonfun$runTestImpl$2.apply(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:33708:8)
[error]   at org.scalatest.FutureOutcome$$anonfun$1.apply(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:34412:9)
[error]   at org.scalatest.FutureOutcome$$anonfun$1.apply(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:34392:8)
[error]   at scala.concurrent.impl.CallbackRunnable.run(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:29377:23)
[error]   at {anonymous}()(C:\DATA\Dev\scalatest-async-issue\target\scala-2.11\root-test-fastopt.js:32715:20)
[error]   at process._tickCallback(node.js:368:9)
```

If we mark any of two tests as ignored then execution will complete successfully.

How to reproduce:

```
git clone https://github.com/nartamonov/scalatest-async-issue.git
sbt test
```

**Comment by bvenners** [comment]
Which version of ScalaTest are you using?

**Comment by nartamonov** [comment]
I use 3.0.0-M15.

**Comment by nartamonov** [comment]
Oops, it looks like I used very outdated version and 3.0.0-RC1 works fine. Sorry, closing issue.
