### ISSUE TITLE
ScalaTest for a Scala.js project fails abruptly: "cannot read 'fileName$1' of undefined"

### ISSUE THREAD

**Issue by fkz** [scalatest/scalatest#926]
I'm using ScalaTest-3.0.0-RC4 to test a Scala.js codebase. When running the tests, they fail abruptly with the error message `cannot read property 'fileName$1' of undefined` and I have no clue why this happens. This seems to be related to scaliest trying to display the position of some failure somehow:

    [error] Reporter completed abruptly with an exception after receiving event: TestFailed(Ordinal(0, 44),ReactLibraryTests() was not equal to List((8,11), (9,11)),SelfRxTest,SelfRxTest,Some(SelfRxTest),selfrx implementation should not remember its value as an event (1),should not remember its value as an event (1),Vector(),Some(org.scalatest.exceptions.TestFailedException: ReactLibraryTests() was not equal to List((8,11), (9,11))),Some(8),Some(IndentedText(- should not remember its value as an event (1),should not remember its value as an event (1),1)),Some(SeeStackDepthException),Some(SelfRxTest),None,main-ScalaTest-running-SelfRxTest,1467719324122).
    [error] TypeError: Cannot read property 'fileName$1' of undefined
    [error]   at org.scalatest.exceptions.StackDepthExceptionHelper$.getFailedCodeFileName(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:15434:35)
    [error]   at org.scalatest.exceptions.StackDepth$class.failedCodeFileName(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:15338:68)
    [error]   at org.scalatest.exceptions.StackDepth$class.failedCodeFileNameAndLineNumberString(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:15349:16)
    [error]   at org.scalatest.tools.StringReporter$.withPossibleLineNumber(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:19242:18)
    [error]   at org.scalatest.tools.StringReporter$.fragmentsForEvent(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:18563:67)
    [error]   at org.scalatest.tools.TaskRunner$SbtLogInfoReporter.apply(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:41883:58)
    [error]   at org.scalatest.tools.SbtReporter.apply(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:30118:17)
    [error]   at org.scalatest.CatchReporter$class.apply(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:8787:21)
    [error]   at org.scalatest.WrapperCatchReporter.apply(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:41608:3)
    [error]   at org.scalatest.Suite$.reportTestFailed(/Users/d066276/src/rx-tests/implementations/selfrx/js/target/scala-2.11/reactive-impl-self-test-fastopt.js:35907:10)

**Comment by fkz** [comment]
this appears to be fixed in 3.0.0
