### ISSUE TITLE
Error using your examples from Scalatest.org

### ISSUE THREAD

**Issue by accesio** [scalatest/scalatest#934]
Hi,

I'm trying to run just the basic example of the ExampleSuite from scalatest.org (http://www.scalatest.org/getting_started_with_junit_4_in_scala)

When compiling using either scalatest 2.2.6 or scalatest 3  I get warnings :   

scala -cp $CLASSPATH ExampleSuite.scala 

warning: Class org.hamcrest.Matcher not found - continuing with a stub.
warning: Class org.hamcrest.Matcher not found - continuing with a stub.
warning: Class org.hamcrest.Matcher not found - continuing with a stub.
warning: Class org.hamcrest.Matcher not found - continuing with a stub.

However, if I try running it , I get an error

scala -cp $CLASSPATH:.  org.junit.runner.JUnitCore ExampleSuite 

JUnit version 4.12
java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
....

So, why is hamcrest required if the compilation claims it isn't required ?

**Comment by rehevkor5** [comment]
Is the dependency that contains that class present on your classpath? Scala, for some reason that I don't understand, sometimes prints that warning if a dependency is marked "runtime" in Maven for example and therefore isn't on the classpath at compilation time.
