### ISSUE TITLE
ScalaTest calls getSimpleName, which is unreliable in a Scala context

### ISSUE THREAD

**Issue by SethTisue** [scalatest/scalatest#992]
the calls have been there for years, so this can't be a common problem, but @travisbrown reports encountering this when upgrading Cats to use ScalaCheck 1.13.3:

```
[info] cats.free.FreeTests *** ABORTED *** (24 milliseconds)
[info]   java.lang.InternalError: Malformed class name
[info]   at java.lang.Class.getSimpleName(Class.java:1330)
[info]   at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl$$anonfun$check$6.apply(CheckerAsserting.scala:141)
```

the (notorious) ticket on `getSimpleName` blowing up on certain Scala classes is https://issues.scala-lang.org/browse/SI-2034

**Comment by melrief** [comment]
I have the same issue, maybe ScalaTest could use something different from `getSimpleName`

**Comment by melrief** [comment]
@SethTisue I can create a replace for `getSimpleName` and use that. If you agree, assign this issue to me.

**Comment by SethTisue** [comment]
(sorry, I am not a ScalaTest maintainer, just an occasional user)

**Comment by bvenners** [comment]
@melrief Yes, please freel welcome to try to come up with a replacement for getSimpleName and submit a PR. That would be very helpful.

**Comment by melrief** [comment]
Uh-oh, sorry @SethTisue but this is the first time somebody that I don't know approaches me and ask me help on a library that is not his library.

@bvenners it will be my pleasure. I'll probably find sometime today or in the next days, judging from the code it shouldn't take too long.

**Comment by travisbrown** [comment]
For anyone who's running into this error when using ScalaTest with ScalaCheck (especially future me), the underlying problem may be a call to `Gen.chooseNum` with bad bounds (e.g. `chooseNum(1, 0)`). Prior to ScalaCheck 1.13 this created a generator that never generated anything, but now it fails with an exception, which ScalaTest swallows and you end up with this "Malformed class name" error. See [this PR](https://github.com/typelevel/cats/pull/1451) for some additional discussion.

**Comment by melrief** [comment]
Thanks @travisbrown, I had your same issue. I think we should anyway fix the usage of the unsafe `getSimpleName` in scalatest to avoid having this kind of errors in future.

**Comment by bvenners** [comment]
Yes, I agree. I'll aim to get it into 3.1.0.

**Comment by drdozer** [comment]
I'm getting this exception. Could we wrap the `Class.getSimpleName` call in something else that doesn't fail? Cheers.

```
java.lang.InternalError: Malformed class name
        at java.lang.Class.getSimpleName(Class.java:1330)
        at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl$$anonfun$check$6.apply(CheckerAsserting.scala:141)
        at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl$$anonfun$check$6.apply(CheckerAsserting.scala:141)
        at org.scalatest.exceptions.PropertyCheckFailedException$$anonfun$$lessinit$greater$1.apply(PropertyCheckFailedException.scala:47)
        at org.scalatest.exceptions.PropertyCheckFailedException$$anonfun$$lessinit$greater$1.apply(PropertyCheckFailedException.scala:47)
        at org.scalatest.exceptions.StackDepthException.message$lzycompute(StackDepthException.scala:156)
        at org.scalatest.exceptions.StackDepthException.message(StackDepthException.scala:156)
        at org.scalatest.exceptions.StackDepthException.getMessage(StackDepthException.scala:186)
        at org.scalatest.Suite$.getMessageForException(Suite.scala:1668)
        at org.scalatest.Suite$.reportTestFailed(Suite.scala:1687)
        at org.scalatest.SuperEngine.runTestImpl(Engine.scala:330)
        at org.scalatest.FreeSpecLike$class.runTest(FreeSpecLike.scala:417)
        at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
        at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:476)
        at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:476)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
        at org.scalatest.FreeSpecLike$class.runTests(FreeSpecLike.scala:476)
        at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
        at org.scalatest.Suite$class.run(Suite.scala:1147)
        at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
        at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:520)
        at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:520)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
        at org.scalatest.FreeSpecLike$class.run(FreeSpecLike.scala:520)
        at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
        at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
        at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
        at sbt.TestRunner.runTest$1(TestFramework.scala:76)
        at sbt.TestRunner.run(TestFramework.scala:85)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
        at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
        at sbt.TestFunction.apply(TestFramework.scala:207)
        at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
        at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by melrief** [comment]
#1044 should fix this your issue @drdozer

**Comment by bvenners** [comment]
Say @melrief did you get an email about a CLA from us?

**Comment by melrief** [comment]
@bvenners no, I've just checked. Can you try again?

**Comment by plinlor** [comment]
Hello @melrief -- @bvenners asked me to post the link for the CLA:
http://www.artima.com/cla/contributorsLicenseAgreement.pdf

**Comment by melrief** [comment]
Compiled, where can I send it?

**Comment by plinlor** [comment]
Here is the process and where to send.  (You may already have done some of this.)  Please:

1.     print-out the CLA, 

2.     complete the contact information, and include your github ‘handle’ as used for the contributions,

3.     sign and date the CLA form, 

then either

· Scan the signed CLA into a PDF, and email the PDF scan to cla@artima.com, or

· Fax the signed CLA to 925.394.7299, or

· Mail the signed CLA to:

        Artima, Inc.
        2070 N Broadway #305
        Walnut Creek, CA 94597 USA
 
Thank you very much!

**Comment by melrief** [comment]
Sent, can we continue now?

**Comment by bvenners** [comment]
Got it. Thanks. We'll make a 3.0.2 with this in it pronto.

**Comment by SethTisue** [comment]
3.0.2 is out, I guess this can be closed now?

**Comment by McBrainy** [comment]
It's great that this is fixed! Can you update your website with the new version so more people don't run into this issue (like I just did)?

**Comment by bvenners** [comment]
We updated the website showing 3.0.4, so closing this one.
